MOV = 1

C1_TAIL = ("A string that does not read from the 600 × 900 proof is blocking; a string that reads is not to be measured. "
           "Any extra text anywhere on the page (a name, a numeral, a label, a stray word on a wall or paper) is blocking. "
           "Spacing around a dash, curly against straight quotes, a hyphen for a dash, and the run length of a repeated letter in a sound cue are nonblocking: the words and their order are what must match.")

DART = ("d'Artagnan, keyed to his sheet: eighteen, long narrow face, sharp chin, long straight nose, close-set quick dark eyes, clean-shaven with no moustache, black unruly hair in his eyes, lean and narrow-shouldered, weight forward, "
        "one hand on a plain swept-hilt rapier too long for him; faded ochre-yellow doublet, brown breeches and boots, grey felt hat with one broken feather, no cloak (default state, pp 1–32).")
ROCH = ("Rochefort, keyed to his sheet: forty, square hard face, heavy black brows, a pale scar from the LEFT temple to the corner of the mouth visible in every panel; straight black hair to the collar, a thin black moustache, no beard; compact, weight back, chin up; "
        "black doublet, black cloak, black hat with a single red feather, the only colour on him (default state, pp 3–34).")
PAIR_DR = "The risky pair here is d'Artagnan and Rochefort: a beardless boy against a scarred man with a thin moustache; ochre against black; a broken grey feather against a red one; weight forward against weight back."

PAGES = {
1: dict(
    title="the yellow horse",
    intent="""Spectacle. A white road between ochre hills under a hot April sky, and riding toward the reader, filling the lower half of the page, a boy of eighteen on an old buttercup-yellow horse: a grey hat with a broken feather, an ochre doublet, and a sword far too long for him. Chin up, entirely pleased with himself. Far behind, small, a farmhouse and a gate. His shadow runs ahead of him down the road. The title card sits over the sky; one caption names Gascony and the year. The dominant turn is simply this: a road out of Gascony, a boy, a yellow horse, a sword too long for him. d'Artagnan owns the page and the horse shares it. The reader turns because a boy this pleased with himself on a horse this yellow is going somewhere. The landscape is scenery; the horse's colour and the boy's chin are the page.""",
    turn="A boy on a ridiculous yellow horse rides straight at the reader with his chin up, and the reader wants to know where he thinks he is going.",
    moments=[
        "One image, the whole page, about 100%: a white road between ochre hills, a line of poplars, a hot morning sky filling the upper third. The boy and the yellow horse ride toward the viewer in the lower half, large, the horse's buttercup coat and the boy's ochre doublet the warmest things in the frame, the too-long sword hanging past his knee, the broken feather in the grey hat, his chin up and his hair in his eyes. Very small behind them on the road, a stone farmhouse and a gate. The boy's shadow stretches ahead of the horse toward the reader.",
        "The title card sits in the open sky at the top, two lines, large and calm, no box. The caption sits lower left over the road, a small matte field, tail-free. Nothing else is lettered.",
    ],
    locks=DART + " The yellow horse, keyed to its plate: an old, calm buttercup-yellow gelding with worn tack; never cream, palomino, dun, or chestnut. No other figures on the page.",
    exclusions="Rochefort, the three Musketeers, and Constance are absent. The father is not on this page. No blood, no wound, no drawn sword: the sword stays sheathed at his hip. The farmhouse stays tiny and unfocal. No name plates, no page number, no lettering on the horse's tack, no signpost with readable words. The title card and the caption are the only text.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/obj-horse.png", "refs/approved/set-road.png"],
    card=[
        ("Title card and caption transcription", "The two-line title card and the one caption read exactly from the 600 × 900 proof, once each, tail-free, in that order top to bottom, with no other text anywhere on the page. " + C1_TAIL),
        ("The page is not a boy on a yellow horse coming at you", "The eye must find one image that is plainly a boy on a bright yellow horse riding toward the reader on a road out of hills, chin up. If the boy is small in a landscape, or the horse is not unmistakably yellow, or the page reads as several panels, the turn has not landed. Landscape detail and sky are nonblocking."),
        ("d'Artagnan does not read as d'Artagnan", "The rider must be a clean-shaven boy with black hair in his eyes, an ochre doublet, a grey hat with a broken feather, and a sword visibly too long for him. A beard, a moustache, a cloak, or a man's age is blocking. Exact patching and boot detail are nonblocking."),
        ("The horse is the wrong horse", "The horse must be old, calm, and buttercup yellow, the only such animal in the book. A brown, white, grey, or cream horse is blocking. Tack detail is nonblocking."),
        ("Focal generation failure", "A duplicated rider, a horse with the wrong number of legs, gross anatomy on the boy's face or hands, or text colliding with the figure is blocking. Distant poplars, farmhouse, and road texture are not."),
    ]),

2: dict(
    title="three gifts at the gate",
    intent="""Illustrated prose, two locations because the turn is the leaving: the farm gate at dawn, then the road north over days. The dominant image is the gate: a grey-haired father in a worn coat with one hand flat on the yellow horse's neck, looking up at the boy in the saddle, and in his other hand a folded cream letter with a red wax seal. The boy looks down at him. The smaller image is the road: the yellow horse going up a long hill in rain and coming down the far side in sun, the boy's hat pulled low. The prose field carries the three gifts and the one rule, and names the boy for the first time. The dominant turn is the three gifts and the one piece of advice, then the road north. The father owns the moment; the boy receives it. The reader turns because the boy has a letter, a sword, a horse, and a rule about fights, and Paris is full of fights. The farm stays subordinate to the two hands: the father's on the horse, the letter in the other.""",
    turn="A father hands a boy a letter, a rule, and a horse at a farm gate, and the reader learns the boy's name and that he has been practising what to say for eleven days.",
    moments=[
        "Panel one, the dominant image, about 60% of the page, close and tall: a stone farm gate at dawn. The father on the LEFT, grey-haired, in a worn coat, standing at the horse's head with one hand flat on the yellow horse's neck, looking up. The boy on the RIGHT in the saddle, hat on, looking down at him. In the father's other hand, raised toward the boy, a folded cream letter with a red wax seal, plainly a sealed letter. Exactly two hands doing the action: one on the horse, one holding the letter. Warm low light from behind the boy.",
        "Panel two, about 40%, a wide strip: the same yellow horse and rider small on a long white road, going up a hill in grey rain and, further along the same strip, coming down the far side in sun, the hat pulled low. No other travellers.",
        "The prose field sits over the pale dawn sky above the gate in panel one, a matte parchment field across most of the page width, never over the two faces, the letter, or the horse's head. Three paragraphs. No other lettering anywhere.",
    ],
    locks=DART + " The father: a grey-haired man of sixty in a worn brown coat, weathered, clean-shaven or stubbled, no hat, no sword, plainly the boy's father and plainly not a Musketeer or a cardinal's man; he is scenery with no balloon and appears only here. The yellow horse keyed to its plate. The letter keyed to the letters plate: a folded cream paper with an unbroken red wax seal.",
    exclusions="Rochefort, the three Musketeers, and Constance are absent. The letter is sealed and whole; it must not be open or broken here. The sword stays sheathed. The father never wears a pointed dark beard, a blue cassock, a red robe, or a scar. No words legible on the letter. No lettering beyond the one prose field: no captions, no sound, no signpost text.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/obj-horse.png", "refs/approved/obj-letters-pass.png", "refs/approved/set-road.png"],
    card=[
        ("Prose transcription", "The prose field reads exactly, all three paragraphs in order, once, from the 600 × 900 proof, placed over plain ground and never over faces or the letter, with no other text on the page. " + C1_TAIL),
        ("The gate does not own the page", "The eye must find first a father at a horse's head handing a sealed letter up to a boy in the saddle, and only second the road. If the road strip competes with the gate, or the letter is not plainly a sealed letter changing hands, the turn has not landed. Judge by what the eye finds, never by area."),
        ("d'Artagnan or the horse fails identity", "The boy must be the same clean-shaven black-haired boy in ochre from the page before, on the same buttercup-yellow horse. A bearded or moustached rider, or a horse of another colour, is blocking."),
        ("The letter is in the wrong state", "The letter must be a folded cream paper with a red wax seal, whole. An opened letter, a broken seal, or a letter with legible words is blocking. Its exact size in the hand is nonblocking."),
        ("Focal generation failure", "Duplicated figures, a father with a Musketeer's or cardinal's look, gross hand anatomy on the two focal hands, or text over a face is blocking. Rain texture and hillside detail are not."),
    ]),

3: dict(
    title="the man in the window",
    intent="""Dramatic. The inn yard at Meung: packed dirt, a well, a stone trough, a stable door, and above the yard a first-floor window with the shutters open. d'Artagnan swings down from the yellow horse at the trough. Leaning on the sill above him, a man in black with a red feather and a pale scar from temple to mouth laughs down at the horse, and two of the inn's men laugh with him. The boy turns, hand on hilt, and invites the man to come down and laugh at him; the man does not fight children, or anyone before dinner; the boy draws and heads for the inn door, and behind him the two men pick up a stool and a broom handle. The dominant turn is the scar laughing at the horse and the boy drawing on him. Rochefort owns the height; d'Artagnan owns the page. The reader turns because the man is not coming down, so the boy is going up. The yard is scenery; the window above and the drawn sword below are the page.""",
    turn="A man with a scar laughs at the yellow horse from a window and refuses to come down, so the boy draws his sword and starts up.",
    moments=[
        "Panel one, about 30%, a wide strip: the inn yard, low horizon. d'Artagnan on the LEFT swinging down from the yellow horse at the stone trough. Above and to the RIGHT, the first-floor window with shutters open and Rochefort leaning on the sill, hat with the red feather, scar on the left side of his face, laughing down. Two inn men in aprons in the yard on the right, laughing. Rochefort's two balloons sit beside the window, stacked, the upper one first, both tails to his mouth at the sill.",
        "Panel two, the dominant panel, about 45%, close and tall: d'Artagnan seen from slightly above, facing the window, hand on the hilt, hair in his eyes, looking up on the LEFT; Rochefort's head and shoulders at the sill on the upper RIGHT, amused. d'Artagnan's balloon upper left with its tail to his mouth; Rochefort's reply lower right, clearly after it, tail to the mouth at the sill.",
        "Panel three, about 25%: d'Artagnan with the long sword out, already halfway to the inn door on the RIGHT, seen from behind the two inn men on the LEFT, one lifting a wooden stool and one a broom handle. The boy's single balloon beside his head, tail to his mouth. The inn men are silent and get no balloons.",
    ],
    locks=DART + " " + ROCH + " " + PAIR_DR + " The two inn men: bareheaded, aproned, heavy, faces generic, no feather, no scar, no beard of the Athos kind; silent. The yellow horse keyed to its plate, at the trough.",
    exclusions="The three Musketeers and Constance are absent. The letter is inside the boy's coat and is not seen. No blood anywhere; nobody is struck on this page. Rochefort stays at the window on every panel; he does not come down here. The horse stays unfocal after panel one. No lettering on the inn sign, the shutters, or the trough; no name plates; no sound cue. Only the five spoken strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/07-rochefort.png", "refs/approved/obj-horse.png", "refs/approved/set-meung-yard.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All five strings read exactly from the 600 × 900 proof, once each, in causal order, each hanging by its tail from the right mouth: Rochefort's two taunts and his refusal from the man at the window, the boy's two lines from the boy in the yard. The inn men carry no balloon. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: a scarred man in a window laughs at the horse, the boy challenges him and is refused, the boy draws and goes for the door. If the eye cannot find the window above and the drawn sword below, or the panels read as equal bands with nothing in charge, the turn has not landed."),
        ("Rochefort does not read as Rochefort", "The man at the window must show one scar across a cheek from temple to mouth (which cheek is nonblocking), a thin moustache and no beard, black clothes, and one red feather. A missing scar, a beard, or a blue cloak is blocking. The exact shape of the window is nonblocking."),
        ("d'Artagnan and Rochefort collide, or d'Artagnan fails", "The boy must be clean-shaven, black-haired, in ochre, with the too-long sword; the man must be older, scarred, in black. If the two could be taken for the same man or the boy has a moustache, blocking."),
        ("Bloodless or state continuity fails", "No blood, no wound, no one struck on this page; the horse is yellow and at the trough; the sword is sheathed in panels one and two and drawn in panel three. A stool already landing on the boy here is blocking; that belongs to the next page."),
        ("Focal generation failure", "A duplicated boy or scar-man, a second red feather in the yard, gross anatomy on the boy's sword hand, or a balloon crossing a face is blocking. Yard texture, well, and background straw are not."),
    ]),

4: dict(
    title="the stool and the letter",
    intent="""Dramatic. The same yard. d'Artagnan at the foot of the inn stairs with his sword up, shouting up the stairwell, does not see the two inn men behind him, one with a stool raised. The stool comes down across the back of his head with one sound, and he goes forward on his face, the sword skidding. Then the man with the scar has come down after all: he crouches by the boy, who is out cold face down in the dirt, and draws the folded cream letter with its red seal out of the inside of the boy's coat. Standing, he reads the address to the light, says the Musketeers, of course, and opens his own black coat to put it away, telling the men to put the boy in the straw. The dominant turn is the scar reading the address and pocketing the letter. Rochefort owns the page; the boy is on the ground for all of it. The reader turns because the man with the scar has the letter and the boy does not know it yet. The knock is a knock, not a wound: no blood, ever.""",
    turn="The boy is knocked cold from behind with a stool, and the scarred man takes the sealed letter out of his coat, reads whom it is for, and pockets it.",
    moments=[
        "Panel one, about 25%, a strip: d'Artagnan on the LEFT at the foot of an outdoor wooden inn stair, sword raised, shouting up; behind him on the RIGHT, unseen by him, the two inn men, one holding a wooden stool up with both hands. The boy's balloon beside his head, tail to his mouth. The inn men are silent.",
        "Panel two, about 20%, a narrow strip: the stool across the back of the boy's head; he pitches forward onto his face in the dirt, the long sword skidding away. The sound cue sits across the panel in large simple letters. No blood, no cut, no mark: a knock.",
        "Panel three, the dominant panel, about 40%, close and tall: Rochefort crouched on the RIGHT beside the boy, who lies face down and out cold on the LEFT, and Rochefort's hand drawing the folded cream letter with the red wax seal out of the inside of the boy's ochre coat. Exactly two hands on the action: Rochefort's hand on the letter and his other hand holding the coat open. His single balloon upper right, tail to his mouth. The scar on the left side of his face toward the viewer.",
        "Panel four, about 15%: Rochefort standing, the letter held up to the light in one hand as he reads the outside of it, his other hand already opening his own black coat. Two balloons stacked on his side, the reading line first, then the order, both tails to his mouth. The inn men, if visible, are small and silent.",
    ],
    locks=DART + " " + ROCH + " " + PAIR_DR + " The two inn men as before: bareheaded, aproned, faces generic, silent. The letter keyed to the letters plate: folded cream paper, red wax seal unbroken on this page, no legible words.",
    exclusions="The three Musketeers and Constance are absent; the yellow horse is out of frame or far back. No blood, no wound, no bruise drawn: the boy is knocked out and lies still, face down, unhurt to the eye. The seal is not broken here. The letter shows no readable writing. No lettering on the stair, the stool, or the inn; only the four spoken strings and the one sound cue. The words Rochefort reads aloud are a balloon, not text on the letter.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/07-rochefort.png", "refs/approved/obj-letters-pass.png", "refs/approved/set-meung-yard.png"],
    card=[
        ("Dialogue transcription or ownership fails", "The boy's shout, the sound cue, and Rochefort's three lines read exactly from the 600 × 900 proof, once each, in causal order; the boy's line hangs from the boy, Rochefort's three from Rochefort; the address he reads aloud is a balloon and no words appear on the letter itself. The run length of the K in the sound cue is nonblocking. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the boy shouts up the stair, a stool knocks him flat, the scarred man takes a sealed letter out of the boy's coat, reads it, and puts it in his own. If the eye does not find the letter leaving the boy's coat as the page's event, the turn has not landed."),
        ("Bloodless fails", "Any blood, cut, bruise, or wound on the boy is blocking. A stool falling and a boy face down and still is the whole injury."),
        ("Rochefort fails identity", "The one scar across a cheek from temple to mouth (which cheek is nonblocking), thin moustache with no beard, all black with one red feather, on every panel he is in. A missing scar or a beard is blocking."),
        ("Letter state fails", "The letter must be a folded cream paper with an unbroken red wax seal, coming out of the boy's coat and going into Rochefort's. A broken seal, an open sheet, or legible writing is blocking. Exact size is nonblocking."),
        ("Focal generation failure", "Exactly two hands on the letter action; a duplicated boy, a third inn man where two were staged, or gross anatomy on Rochefort's reading hand is blocking. Straw, dirt, and stair texture are not."),
    ]),

5: dict(
    title="then so do I",
    intent="""Dramatic. Evening in the stable at Meung: d'Artagnan sits up in the straw with a hand on the back of his head, his hat beside him, his other hand inside his coat with the inside pocket turned out and empty, the yellow horse looking down at him from the next stall. Then the yard at dusk, empty: the boy standing in the middle of it looking up at the window, whose shutters are closed, the stable door open on one empty stall, nobody laughing now, nobody there at all. A caption says what the boy sees and that the inn watched the black horse go; the boy says the stable boy told him the man rode for Paris at noon, with the letter. Then the boy in the saddle at a gallop out of the gate: then so do I. The dominant turn is the letter gone and the boy riding after it. d'Artagnan owns the page alone. The reader turns because the letter that was going to open Paris is in the pocket of the man he most wants to fight.""",
    turn="The boy wakes to an empty pocket, an empty stall, and a shut window, and rides for Paris after the man who took his letter.",
    moments=[
        "Panel one, about 30%: the stable at evening, the boy sitting up in straw on the LEFT, one hand at the back of his head, his hat beside him, the other hand inside his ochre coat with the inside pocket pulled out and hanging empty and plainly visible. The yellow horse's head looks down over the stall partition on the RIGHT. The boy's single balloon beside his head, tail to his mouth.",
        "Panel two, the dominant panel, about 45%, tall: the yard at dusk seen wide and empty, the boy small in the middle of it looking up at the first-floor window, whose shutters are shut; beside him the stable door open on one empty stall. No inn men, no laughter, nobody. The caption sits upper left over the dark wall, tail-free. The boy's balloon sits lower on his side, tail to his mouth.",
        "Panel three, about 25%, a strip: the boy in the saddle, hat jammed on, the yellow horse at a gallop out through the yard gate onto the road north, seen from the side. His single balloon beside him, tail to his mouth.",
    ],
    locks=DART + " The yellow horse keyed to its plate. No other figures: the stable boy is not shown, only quoted.",
    exclusions="Rochefort is absent from this page and must not appear at the window or in the yard; the shutters are closed. The three Musketeers and Constance are absent. No blood, no bruise, no bandage on the boy's head. The empty stall is empty. The letter is not on this page. No lettering on the inn, the shutters, or the gate; only the three spoken strings and the one caption.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/obj-horse.png", "refs/approved/set-meung-yard.png"],
    card=[
        ("Dialogue transcription or ownership fails", "The boy's three lines and the caption read exactly from the 600 × 900 proof, once each, in causal order; the caption is tail-free and the three balloons hang from the boy. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: he wakes with an empty pocket, he stands in an empty yard under a shut window, he rides out after the man. If the empty yard under the shut window is not the largest image the eye finds, or the pocket's emptiness does not read, the turn has not landed."),
        ("Rochefort appears", "Any figure with a scar, a red feather, or a black horse on this page is blocking; the point of the page is that he is gone."),
        ("d'Artagnan or the horse fails identity", "The clean-shaven black-haired boy in ochre and the buttercup-yellow horse must be the same as on the pages before. A moustache, a cloak, or another horse colour is blocking."),
        ("Bloodless or state fails", "No blood, bandage, or wound on the boy's head. The turned-out pocket must read as empty. The stall must read as empty."),
        ("Focal generation failure", "A duplicated boy, two horses, gross anatomy on the hand at the pocket, or a balloon across the boy's face is blocking. Straw and dusk texture are not."),
    ]),

6: dict(
    title="Paris",
    intent="""Spectacle. From the top of the last hill: Paris, grey-blue slate roofs stacked to the horizon, a brown river, stone bridges with houses built on them, spires, smoke, and a road going down into it full of carts and people. In the foreground, small, the boy on the yellow horse with his hat off, staring. One caption. The dominant turn is Paris itself: the size of it, and that nobody looks up. The city owns the page; the boy is a small figure with his hat off. The reader turns because nobody here knows his name, and he has lost the one thing that would have told them. The crowd on the road is scenery: many small figures, no faces, no balloons.""",
    turn="A boy who has never seen three hundred people at once sees all of Paris from the last hill, and none of it looks up.",
    moments=[
        "One image, the whole page, about 100%: the view down from the last hill into Paris, the road descending in the lower left and filling with carts, riders, and walking figures, all small, all faceless, none looking back; the city spreading up the page to a high horizon: grey-blue slate roofs stacked and crowded, a brown river crossing the middle distance with stone bridges carrying houses, spires and chimney smoke, overcast light with the sun somewhere behind cloud. In the near foreground, lower centre, small against all that, the boy on the yellow horse, hat in his hand, staring.",
        "The caption sits lower right over the road, one matte field, tail-free. No other lettering anywhere: no signs, no shop boards, no readable words on the bridges.",
    ],
    locks=DART + " The yellow horse keyed to its plate. Every other figure is scenery: small, faceless, no reserved identity stack, no balloon.",
    exclusions="Rochefort, the three Musketeers, and Constance are absent; no red feather, no blue cassock, no red cassock anywhere in the crowd. No lettering except the one caption. The boy stays small; the city is the page. No blood, no drawn sword.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/obj-horse.png", "refs/approved/set-paris.png"],
    card=[
        ("Caption transcription", "The one caption reads exactly from the 600 × 900 proof, once, tail-free, with no other text anywhere on the page including on signs, bridges, or shop fronts. " + C1_TAIL),
        ("The page is not Paris seen from above by a small boy", "The eye must find a whole city of stacked roofs, a river, and bridges with houses on them, and then a small boy on a yellow horse looking at it with his hat off. If the boy is large and the city is a backdrop, or the page splits into panels, the turn has not landed."),
        ("d'Artagnan or the horse fails identity", "The small rider must still be a clean-shaven boy in ochre with a grey hat in his hand on a buttercup-yellow horse. A wrong horse colour is blocking; face detail at this size is nonblocking so long as nothing contradicts him."),
        ("A locked absentee appears", "Any figure in the crowd with a red feather and scar, a blue cassock with a white cross, or a red cassock is blocking on this page."),
        ("Focal generation failure", "A duplicated rider, a corrupted city block that reads as a second image, or text colliding with the rider is blocking. Crowd repetition and roof texture are not."),
    ]),

7: dict(
    title="the door and the scar",
    intent="""Dramatic. A great arched carriage door in a stone wall, open on a courtyard full of blue cloaks, horses, and noise, and in the arch a porter with a halberd who does not move. d'Artagnan on the step, hat in his hands, small, explaining that his father was the Captain's friend and that a man stole the letter. The door closes in his face; behind it, blue cloaks laugh; a caption says the door closed the way doors close on boys. He turns on the step, and across the street, on a black horse, in black with one red feather, is the scar, looking straight at him and smiling. The boy shouts; the man turns the horse into the crowd without hurry, taunting him for being on foot; the boy is already running with a hand on his hilt, and at the edge of the last panel a tall blue-cloaked shoulder comes round the corner into his path. The dominant turn is the gate shutting and the scar across the street. Rochefort owns the taunt; d'Artagnan owns the running. The reader turns because he is running and there is a man in his way.""",
    turn="The Musketeers' door closes on a boy with no letter, and across the street the man who took it is smiling from a black horse, so the boy runs.",
    moments=[
        "Panel one, about 30%, a strip: the great arched door in a stone wall on the RIGHT, standing open on a courtyard of blue-cassocked Musketeers, horses, and noise; the porter with a halberd in the arch, faceless and still; d'Artagnan on the LEFT on the step, hat in both hands, small against the arch. His single balloon beside his head, tail to his mouth.",
        "Panel two, about 25%, a strip: the door closing in the boy's face, seen from his side, a slice of laughing blue cloaks visible through the narrowing gap. The caption sits over the closing door, tail-free. The boy is silent here.",
        "Panel three, the dominant panel, about 45%, close and tall: the boy turned round on the step in the lower LEFT foreground, and across the street on the RIGHT, on a black horse, Rochefort in black with the red feather, scar toward the viewer, looking straight at the boy and smiling. The boy's balloon upper left, tail to his mouth.",
        "Panel four, small: Rochefort turning the black horse into the crowd without hurry on the RIGHT, his balloon beside him, tail to his mouth; the boy already running toward him on the LEFT with a hand on his hilt; at the extreme left edge, entering the frame, a tall blue-cloaked shoulder and a black sling, nothing more of that man.",
    ],
    locks=DART + " " + ROCH + " " + PAIR_DR + " The porter: a heavy man with a halberd, plain coat, faceless, silent. Musketeers in the courtyard: blue cassocks with the white cross, clean-shaven or full-bearded, never a dark pointed beard, never red-brown curls with a waxed moustache, never blond curls; faceless where possible; no balloons. The shoulder at the edge of panel four is Athos's blue cassock and black sling only, no face.",
    exclusions="Constance, Porthos, and Aramis are absent. Athos is not on this page beyond a shoulder and a sling at the edge of the last panel. No blood. The father's letter is not on this page. Rochefort stays across the street and never dismounts. No lettering on the gate, the wall, or any shop; no name plates; only the four strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/07-rochefort.png", "refs/approved/set-paris.png"],
    card=[
        ("Dialogue transcription or ownership fails", "The boy's plea, the caption, the boy's shout, and Rochefort's taunt read exactly from the 600 × 900 proof, once each, in causal order; the boy's two lines hang from the boy, Rochefort's from the mounted man; the caption is tail-free; the porter and the courtyard carry no balloons. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the boy pleads at the gate, the door closes on him, he turns and sees the scar across the street, he runs. If the door closing and the scar's smile are not the two images the eye finds, or the last panel does not show him running, the turn has not landed."),
        ("Rochefort fails identity or is not mounted", "The man across the street must be on a black horse, in black, with one red feather, one scar across a cheek from temple to mouth (which cheek is nonblocking), thin moustache, no beard. A beard, a blue cloak, or a scarless face is blocking."),
        ("d'Artagnan fails identity", "Clean-shaven, black hair in his eyes, ochre doublet, grey hat in his hands in panel one, the too-long sword. A moustache or a cloak is blocking."),
        ("A background figure wears a lock", "Any courtyard Musketeer with a dark pointed beard and shoulder-length hair, red-brown curls and a waxed moustache, or blond curls and a small moustache is blocking; the porter must not have a scar or a red feather."),
        ("Focal generation failure", "A duplicated boy, two scar-men, gross anatomy on the boy's hands holding the hat, or a balloon crossing a face is blocking. Courtyard horses and crowd repetition are not."),
    ]),
}
