MOV = 2
from mov1 import C1_TAIL, DART, ROCH, PAIR_DR

ATHOS_SLING = ("Athos, keyed to his sheet's sling view: thirty, the tallest man in the book, long pale face, hooded level grey eyes, lines beside the mouth, dark hair straight to the shoulder, a short pointed dark beard and neat moustache, lean; "
               "blue cassock with the white cross over a black doublet, black hat with one white plume; LEFT arm in a black cloth sling (sling state, pp 8–16); good hand on the pommel of his grounded sword; the one man in any panel not moving.")
PORTHOS = ("Porthos, keyed to his sheet: thirty-five, enormous, the widest man in the book, barrel chest, round ruddy face, small bright eyes, big nose, red-brown curls to the collar, a great red-brown moustache waxed to points, no beard; chest out, fists on hips; "
           "blue cassock with the white cross over a crimson doublet, a wide baldric embroidered with gold across the front, black hat with three red ostrich plumes, the largest hat in the book, a gilt-hilted sword; a hand smoothing the baldric.")
ARAMIS = ("Aramis, keyed to his sheet: twenty-four, slim, fine oval face, small straight nose, large dark eyes, pale skin, fine blond curls to the collar always in order, a small neat blond moustache and lip tuft, no beard; weight on one hip, two fingers at his moustache; "
          "immaculate blue cassock with the white cross over dove grey with a wide white lace collar, black hat with one white plume, slim silver-hilted sword, a small book at his belt.")
PAIR_AR = "The risky pair is Athos and Rochefort: a short pointed dark beard against a thin moustache and no beard; no scar against the scar; the tallest man against middle height; blue with the white cross against all black; a white plume against a red feather; stillness with a hand on the pommel against weight back and chin up."
THREE = "The three Musketeers are separated by mass, hair colour, and facial hair before anything else: Athos tall, dark, pointed beard, still; Porthos huge, red-brown curls, waxed moustache, gold baldric, red plumes; Aramis slim, blond, small moustache, lace collar, book."
GUARDS = "The Cardinal's guards: red cassocks with a white cross, plain steel morions or wide hats with no feather, faces generic and turned away, never a scar, never a pointed beard; silent, no balloons."

PAGES = {
8: dict(
    title="a shoulder in the way",
    intent="""Dramatic. A Paris street corner. d'Artagnan, at a dead run after the scar, goes straight into the sling of a very tall Musketeer, and the tall man goes white. This is Athos: very tall, very still, grey eyes, his good hand holding his bad shoulder, while the boy, already two steps past, looks back over his own shoulder for the man who has vanished. The tall man observes that the shoulder was hurt before the boy arrived; the boy apologises and says he cannot stop; the tall man says he has stopped. Face to face, the boy offers satisfaction and never refuses a fight; the tall man names the field behind the Carmelite convent at noon and tells him to bring a friend to stand with him; the boy has none. The dominant turn is Athos's shoulder and the appointment at noon. Athos owns the stillness, d'Artagnan the heat. The reader turns because the boy has a duel at noon with the tallest man in Paris and has lost the scar. The street is scenery; the sling and the two faces are the page.""",
    turn="Running after the scar, the boy slams into a Musketeer's bandaged shoulder, and by the end of the panel he has a duel at noon and no friend to bring.",
    moments=[
        "Panel one, about 30%, a strip: the corner of a narrow Paris street, the boy in ochre on the LEFT at a full run colliding shoulder-first into the black sling of a very tall Musketeer in blue on the RIGHT, the impact the centre of the strip. The sound cue at the collision in large simple letters. No balloons here.",
        "Panel two, the dominant panel, about 45%, close and tall: Athos on the RIGHT, very tall, very still, white-faced, his good hand holding the slung shoulder; the boy on the LEFT already two steps past him, twisted to look back over his own shoulder up the street for the vanished scar. Three balloons in A–B–A order: Athos's first line upper right by his mouth, the boy's apology middle left by his, Athos's two-word answer lower right, clearly third, tail to Athos's mouth.",
        "Panel three, about 25%: face to face, the boy on the LEFT hot, Athos on the RIGHT level and a head taller. Three balloons in A–B–A order: the boy's challenge upper left, Athos's appointment middle right, the boy's last line lower left, each tail to its own mouth, the reply never level with the line that prompts it.",
    ],
    locks=DART + " " + ATHOS_SLING + " The risky pair on this page by type is Athos against the absent Rochefort; keep Athos's pointed beard, blue cassock, white plume, and sling so he can never be taken for the scar. Passers-by are scenery, faceless, no balloons.",
    exclusions="Rochefort is absent from this page: no red feather, no scar, no black horse anywhere in the street. Porthos, Aramis, and Constance are absent. No blood: the sling is an old injury already bandaged, nothing is drawn as a wound. The boy's sword stays sheathed. No lettering on shop signs or walls; only the six spoken strings and the one sound cue.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/02-athos.png", "refs/approved/set-paris.png"],
    card=[
        ("Dialogue transcription or ownership fails", "The sound cue and all six lines read exactly from the 600 × 900 proof, once each, in causal order; each of Athos's three lines hangs by its tail from the tall man in the sling and each of the boy's three from the boy; in both three-line exchanges the reply sits clearly after the line it answers. The run length of the sound cue's letters is nonblocking. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the boy runs into a slung shoulder, the tall man stops him with two words, the duel is set for noon and the boy has no friend. If the eye does not find the tall still man holding his shoulder as the page's image, the turn has not landed."),
        ("Athos fails identity", "Tall, dark shoulder-length hair, short pointed beard, blue cassock with the white cross, white plume, LEFT arm in a black sling. A scar, a red feather, black clothes, no beard, or the sling on the right arm is blocking."),
        ("d'Artagnan fails identity", "Clean-shaven, black hair in his eyes, ochre doublet, grey hat, too-long sword sheathed. A moustache or a cloak is blocking."),
        ("Bloodless fails", "No blood, no visible wound; the sling is clean cloth over a healed hurt."),
        ("Focal generation failure", "A duplicated Athos or boy, an extra slung arm, gross anatomy on Athos's hand at the shoulder, or a balloon across a face is blocking. Street texture and passers-by are not."),
    ]),

9: dict(
    title="the baldric",
    intent="""Dramatic. A second corner. Porthos, enormous, red-brown curls and a waxed moustache, fills the street telling two blue cloaks a story about the Cardinal with his own cloak thrown back to show a baldric embroidered in gold; the boy, ducking past at a run, goes straight into the cloak. On the ground, tangled in it, he sees what the whole street now sees: the back of the baldric is plain buff leather, no gold at all. The boy says so. Porthos, scarlet, fists on hips, will not have the street told about the back of his baldric; the boy offers one o'clock behind the Carmelites since noon is taken; Porthos asks who has him at noon; a tall man with a bad shoulder; Athos! Porthos will take whatever he leaves. The dominant turn is the cloak coming off the baldric. Porthos owns the page; the boy is on the ground for most of it. The reader turns because that is two duels an hour apart and the boy is still running. The two listening Musketeers are scenery.""",
    turn="The boy tangles in a huge Musketeer's cloak and exposes the plain leather back of his gold baldric to the street, and gets a second duel at one o'clock.",
    moments=[
        "Panel one, about 30%, a strip: Porthos on the RIGHT, enormous, cloak thrown back over one shoulder so the gold-embroidered front of the wide baldric shows, mid-story to two blue-cloaked Musketeers on the far right; the boy on the LEFT at a run, ducking, already going into the hanging cloak. Porthos's single balloon upper right, tail to his mouth.",
        "Panel two, the dominant panel, about 45%, close and tall: the boy on the ground on the LEFT, tangled in the fallen cloak, looking up; Porthos on the RIGHT turning, seen from behind and to the side so that the BACK of the baldric is plainly in view across the blue cassock: plain buff leather, no gold. The two Musketeers staring at it. The boy's single balloon lower left, tail to his mouth.",
        "Panel three, about 25%, staged as single-speaker beats read left to right: Porthos scarlet, fists on hips, towering, on the RIGHT with his two lines stacked on his side; the boy on the LEFT, up on one knee, with his two lines stacked on his side, in the order Porthos, boy, Porthos, boy, Porthos as five balloons: Porthos's threat upper right, the boy's offer upper left below it, Porthos's question middle right, the boy's answer middle left, Porthos's last line lowest right. Each tail to its own mouth; no two balloons level.",
    ],
    locks=DART + " " + PORTHOS + " The two listening Musketeers: blue cassocks with the white cross, clean-shaven or full-bearded, never a pointed dark beard, never blond curls; faceless where possible; silent.",
    exclusions="Athos, Aramis, Rochefort, and Constance are absent. The baldric's back is plain leather with no gold, and it is seen on this page only. No blood. The boy's sword stays sheathed. No lettering on the baldric, the cloak, or any shop; only the seven spoken strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/03-porthos.png", "refs/approved/set-paris.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All seven lines read exactly from the 600 × 900 proof, once each, in causal order; the Porthos lines hang from the huge red-moustached man and the boy's from the boy on the ground; in the five-line exchange each reply sits after the line it answers. The two listening Musketeers carry no balloon. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the boy runs into the cloak, the cloak comes off and the back of the baldric is plain leather, the huge man demands a duel and gets one at one o'clock. If the plain leather back of the baldric is not plainly the thing the eye finds in the largest image, the turn has not landed."),
        ("Porthos fails identity", "Enormous, round ruddy face, red-brown curls, waxed moustache with no beard, blue cassock over crimson, gold-fronted baldric, three red plumes. A beard, a slim build, or dark straight hair is blocking."),
        ("The baldric state is wrong", "In the dominant panel the back of the baldric must be plain buff leather with no gold; gold on the back is blocking. Exact embroidery pattern on the front is nonblocking."),
        ("d'Artagnan fails identity", "Clean-shaven, black-haired, ochre, no cloak of his own; the cloak he is tangled in is Porthos's blue one."),
        ("Focal generation failure", "A duplicated Porthos, three listening Musketeers where two were staged, gross anatomy on Porthos's fists, or text across a face is blocking. Street texture is not."),
    ]),

10: dict(
    title="the handkerchief",
    intent="""Dramatic. A third corner. Aramis, slim, blond, immaculate, stands with two blue cloaks by a wall with one boot planted on a white lace handkerchief bearing a small embroidered monogram. The boy, slowing at last, sees it, stoops, and pulls it out from under the boot with the observation that it is a lady's. Aramis takes it between two fingers, icy, denying he dropped anything, that it is his, that he has seen it, and that he was standing on it on purpose; the boy asks then why he is taking it. Two fingers at his moustache, perfectly polite, Aramis explains the boy has embarrassed him and will have to be killed at two o'clock; two is free, noon and one are taken; how busy you are. The dominant turn is the handkerchief and the appointment at two. Aramis owns the page's manners; the boy owns its innocence. The reader turns because that is three duels on one field and not one friend in the world. The two listening cloaks are scenery.""",
    turn="The boy hands a blond Musketeer the lady's handkerchief he was pretending not to stand on, and gets his third duel of the afternoon.",
    moments=[
        "Panel one, about 30%, a strip: a stone wall, Aramis on the RIGHT with two blue-cloaked Musketeers beyond him, one boot planted on a white lace handkerchief on the cobbles; the boy on the LEFT, slowing, stooping, his fingers on the handkerchief's edge drawing it out from under the boot. The boy's single balloon upper left, tail to his mouth.",
        "Panel two, the dominant panel, about 45%, close and tall: Aramis on the RIGHT taking the handkerchief between two fingers, icy, the small monogram visible but not legible; the two Musketeers looking at it and then at him; the boy on the LEFT, puzzled. Two balloons: Aramis's long denial upper right, tail to his mouth; the boy's question lower left, clearly after it, tail to his.",
        "Panel three, about 25%, one panel, not split: Aramis on the LEFT, two fingers at his moustache, and the boy on the RIGHT, face to face. Three balloons in strict top-to-bottom order, A–B–A: Aramis's invitation at the top on the left, tail to his mouth; the boy's answer below it on the right, tail to his; Aramis's last line lowest on the left, tail to his. The boy's balloon must sit clearly below the invitation so it cannot be read first.",
    ],
    locks=DART + " " + ARAMIS + " The risky pair here is d'Artagnan and Aramis, two young men: black rough hair against blond curls; no moustache against a small neat one; ochre with no cloak against the blue cassock and lace collar; weight forward against weight on one hip. The two listening Musketeers: blue cassocks, clean-shaven or full-bearded, never blond, never a pointed dark beard; silent.",
    exclusions="Athos, Porthos, Rochefort, and Constance are absent. The handkerchief carries a small embroidered monogram, not a crown, and no legible letters. No blood. The boy's sword stays sheathed. No lettering on the wall; only the six spoken strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/04-aramis.png", "refs/approved/set-paris.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All six lines read exactly from the 600 × 900 proof, once each, in causal order; Aramis's three from the slim blond man, the boy's three from the boy; in each exchange the reply sits after the line it answers. The two listening Musketeers carry no balloon. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the boy pulls a lace handkerchief from under a boot, the blond man denies it and takes it, and sets a duel for two o'clock. If the handkerchief passing from boot to fingers is not the image the eye finds, the turn has not landed."),
        ("Aramis fails identity or collides with d'Artagnan", "Aramis must be slim, blond, with a small neat moustache, lace collar, blue cassock, book at the belt; the boy must be black-haired and clean-shaven in ochre. If either could be the other, or Aramis has a beard or dark hair, blocking."),
        ("The handkerchief fails", "It must be a white lace handkerchief, first under a boot then between two fingers; a crown emblem or legible letters on it is blocking. The exact monogram shape is nonblocking."),
        ("Focal generation failure", "A duplicated Aramis, a third listener, gross anatomy on the two fingers holding the handkerchief, or text across a face is blocking."),
    ]),

11: dict(
    title="a quarter to twelve",
    intent="""Illustrated prose, two locations because the memory is the turn's other half: a stone bench by the river, and the farm gate remembered. The dominant image is the boy alone on the bench with his sword across his knees and his hat pushed back, the city going about its business behind him and a church clock over the roofs at a quarter to twelve. The smaller image is warm and far: the farm gate, his father's hand on the horse's neck. The prose counts what he has, remembers the rule and that his father never said what to do with three, and sends him to the field at a quarter to twelve because he said he would. The dominant turn is an hour on a bench with three duels and no friend, and standing up anyway. d'Artagnan owns the page alone. The reader turns because he is walking to a field where three men are waiting to fight him, because he said so. The river and the crowd stay subordinate to the boy and the clock.""",
    turn="A boy sits on a bench by the river for an hour with three duels and no friend, remembers his father's rule, and stands up at a quarter to twelve.",
    moments=[
        "Panel one, the dominant image, about 65%, close and tall: the boy alone on a stone bench on a river quay, the too-long sword laid across his knees, hat pushed back, elbows on his thighs, looking at nothing. Behind him, across the brown river, Paris going about its business, small and indifferent, and over the roofs a church clock face reading a quarter to twelve: hands only, no numerals needed to be legible. Grey light.",
        "Panel two, about 35%, small and warm: the farm gate from page two, remembered: the father's hand flat on the yellow horse's neck, the boy above him, all softer and further away.",
        "The prose field sits over the flat grey river in panel one, a matte parchment field across most of the width, never over the boy, the clock, or the memory. Three paragraphs. No other lettering; the clock shows no numerals.",
    ],
    locks=DART + " The father and the yellow horse in the memory panel are the same as on page two: grey-haired man in a worn coat, buttercup-yellow horse. Every other figure is faceless scenery.",
    exclusions="Athos, Porthos, Aramis, Rochefort, and Constance are absent; no blue cassock close enough to have a face; no red feather anywhere. The sword stays sheathed on his knees. No blood. The clock carries no readable numerals or letters; no shop signs; only the one prose field.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/obj-horse.png", "refs/approved/set-paris.png"],
    card=[
        ("Prose transcription", "The prose field reads exactly, all three paragraphs in order, once, from the 600 × 900 proof, over plain ground and never over the boy's face or the clock, with no other text on the page including on the clock face. " + C1_TAIL),
        ("The bench does not own the page", "The eye must find a boy alone on a bench by a river with a sword across his knees, and a clock near noon over the roofs, before it finds the small warm memory of the gate. If the memory competes, or the page reads as a comic strip, the turn has not landed."),
        ("d'Artagnan fails identity", "Clean-shaven, black hair, ochre, grey hat pushed back, the too-long sword. A moustache or a cloak is blocking."),
        ("The memory contradicts page two", "The remembered gate must show the grey-haired father and the yellow horse; another horse colour or a bearded Musketeer-looking father is blocking. Softness and distance are expected."),
        ("Focal generation failure", "A duplicated boy on the quay, a clock with garbled numerals that read as text, or the prose field over a face is blocking. Crowd and river texture are not."),
    ]),

12: dict(
    title="noon, and five red cloaks",
    intent="""Dramatic. The field behind the Carmelite convent at noon: long grass, a high wall of yellow stone, one big tree, a stone trough, and a gap in the wall. Athos under the tree, arm in the sling, good hand on the pommel of his grounded sword. The boy arrives, hat off; Athos observes that most boys don't come; the boy says he said he would and that Athos's friends aren't here; they are. Porthos and Aramis come through the gap and stop dead: that's my one o'clock; that is my two o'clock; he's my noon. The three look at one another and laugh, Porthos with his head back, Aramis behind his hand, Athos with one corner of his mouth, and the boy does not laugh; and behind all four, coming through the gap, five red cloaks with white crosses and, in front of them, in black, the scar, who forbids duelling, will take their swords, and will take the Gascon himself. The dominant turn is the three working it out and laughing, and the red cloaks coming round the wall. The reader turns because it is five red against three blue, one of them one-armed, and the scar has just claimed the boy.""",
    turn="The three Musketeers discover the boy has challenged all of them and laugh, and the Cardinal's guards come through the wall behind them with the scar in front.",
    moments=[
        "Panel one, about 25%, a strip: the meadow at noon, Athos on the RIGHT under the big tree, LEFT arm in the sling, good hand on the pommel, sword point on the ground; the boy on the LEFT arriving, hat off. Three balloons A–B–A: Athos upper right, the boy middle left, Athos's two words lower right, clearly third, tails to each mouth.",
        "Panel two, about 30%, as single-speaker beats read left to right in a strip cut in three: Porthos on the LEFT stopped dead in the gap in the wall with his line; Aramis in the MIDDLE beside him with his; Athos on the RIGHT under the tree with his. One balloon each, each tail to its own mouth, read left to right.",
        "Panel three, the dominant panel, about 45%, close and tall: the three Musketeers in the foreground looking at one another and laughing, Porthos head back, Aramis behind his hand, Athos with one corner of his mouth, the boy among them not laughing; and behind them, through the gap in the yellow wall, five guards in red cassocks with white crosses and, in front of them, Rochefort in black with the red feather, scar toward the viewer. Porthos's line upper left, tail to his mouth; Rochefort's two lines stacked upper right beside him, tails to his mouth, the forbidding line first.",
    ],
    locks=DART + " " + ATHOS_SLING + " " + PORTHOS + " " + ARAMIS + " " + ROCH + " " + THREE + " " + PAIR_AR + " " + GUARDS,
    exclusions="Constance is absent. No blood; no sword is drawn on this page except Athos's grounded one. The guards stay behind Rochefort and carry no balloons. The trough is present but unfocal. No lettering on the wall or the convent; only the nine spoken strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/02-athos.png", "refs/approved/03-porthos.png", "refs/approved/04-aramis.png", "refs/approved/07-rochefort.png", "refs/approved/set-carmelite-field.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All nine lines read exactly from the 600 × 900 proof, once each, in causal order, and each hangs by its tail from its owner: Athos's three from the tall slung man, the boy's one from the boy, Porthos's two from the huge red-moustached man, Aramis's one from the slim blond, Rochefort's two from the scarred man in black. The three one-o'clock, two-o'clock, noon lines must read left to right from three different mouths. Guards carry no balloon. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the boy arrives to Athos, the other two arrive and each claims his hour, the three laugh, and red cloaks with the scar come through the wall behind them. If the laughing three with the guards behind is not the image the eye finds, the turn has not landed."),
        ("The three Musketeers collide", "Athos tall, dark, pointed beard, sling; Porthos huge, red curls, waxed moustache, gold baldric; Aramis slim, blond, small moustache. If any two cannot be told apart by mass, hair, and beard, blocking."),
        ("Athos and Rochefort collide, or Rochefort fails", "Rochefort in black with the red feather, one scar across a cheek from temple to mouth (which cheek is nonblocking), thin moustache, no beard; Athos in blue with the white plume, pointed beard, sling. If either could be the other, blocking."),
        ("Guards or continuity fail", "Exactly five guards in red cassocks with white crosses, faces turned away, none with a scar or a feather; more or fewer than five is blocking. The sling on Athos's LEFT arm. No blood."),
        ("Focal generation failure", "A duplicated Musketeer, two scar-men, a sixth guard, gross anatomy on any laughing face, or a balloon across a face is blocking. Grass and wall texture are not."),
    ]),

13: dict(
    title="four of us",
    intent="""Dramatic. The field. Athos, Porthos, and Aramis draw in a line facing the five guards and Rochefort; the boy stands off to one side between the two groups with his sword still sheathed. Athos counts three of them, five of those, one of him in a sling, and says it will do; Porthos tells the boy to stand back, this is not his fight, he is not one of them. The boy draws his father's sword and steps into the line beside Athos: he hasn't got the cloak, he has the sword and the heart and he is standing here; four of us. Athos looks down at him properly for the first time and asks his name; d'Artagnan; then, d'Artagnan, the one on the left is yours, don't get hurt, I'd have to explain it. The dominant turn is the boy picking a side. d'Artagnan owns the page; Athos gives him his name back. The reader turns because he has picked the side with fewer swords. The guards and Rochefort wait, silent.""",
    turn="Told he is not one of them, the boy draws and steps into the line beside Athos, and Athos asks his name.",
    moments=[
        "Panel one, about 30%, a strip: the three Musketeers on the LEFT drawing, in a line, Athos one-handed, facing the five red cloaks and Rochefort on the RIGHT; the boy in the middle distance between the groups, off to one side, sword still sheathed. Two balloons stacked on the left over the line: Athos's count first, upper, tail to Athos; Porthos's order below it, tail to Porthos.",
        "Panel two, the dominant panel, about 45%, close and tall: the boy drawing the too-long sword and stepping into the line beside Athos, seen low and large, the boy on the LEFT of Athos, both facing right. Two balloons stacked on the boy's side, the long line first and the three-word line below it, both tails to the boy's mouth. Exactly two hands on the sword.",
        "Panel three, about 25%, as single-speaker beats: Athos on the RIGHT looking down at the boy, the boy on the LEFT looking up. Three balloons A–B–A: Athos's question upper right, the boy's name middle left, Athos's last line lower right, each tail to its own mouth.",
    ],
    locks=DART + " " + ATHOS_SLING + " " + PORTHOS + " " + ARAMIS + " " + ROCH + " " + THREE + " " + PAIR_AR + " " + GUARDS,
    exclusions="Constance is absent. No blood; no blade touches anyone on this page. Rochefort and the guards are present, silent, waiting on the right, with no balloons. No lettering on the wall; only the seven spoken strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/02-athos.png", "refs/approved/03-porthos.png", "refs/approved/04-aramis.png", "refs/approved/07-rochefort.png", "refs/approved/set-carmelite-field.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All seven lines read exactly from the 600 × 900 proof, once each, in causal order; Athos's three from the tall slung man, Porthos's one from the huge man, the boy's three from the boy; in the name exchange the reply sits after the question. Rochefort and the guards carry no balloon. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the three draw and tell the boy to stand back, the boy draws and steps into the line, Athos asks his name and gives him the man on the left. If the boy stepping into the line is not the largest image the eye finds, the turn has not landed."),
        ("The Musketeers collide or Athos and Rochefort collide", "As on the page before: three separable Musketeers; Rochefort scarred, black, red feather; Athos bearded, blue, sling. Blocking if any pair merges."),
        ("d'Artagnan fails identity", "Clean-shaven, black-haired, ochre, no cloak, drawing a plain swept-hilt rapier too long for him. A moustache or a blue cassock on the boy is blocking."),
        ("Guards, sling, or bloodless fail", "Five red-cassocked guards, faces away, no feather; Athos's sling on the LEFT arm; no blood, no contact."),
        ("Focal generation failure", "Exactly two hands on the boy's drawn sword; a duplicated boy, a sixth guard, or gross anatomy on Athos's face looking down is blocking."),
    ]),

14: dict(
    title="the best fight of his life",
    intent="""Spectacle. The whole fight in one picture, top to bottom: Porthos lifting a red-cloaked guard bodily off the ground and into the trough; Aramis's blade pinning a guard's hat to the yellow wall through the brim, the guard bareheaded and astonished beneath it; Athos, one-handed, stepping aside from a lunge so neatly the guard runs straight into the tree; and in the middle, fast, the boy in ochre with his hair flying, driving a guard backward across the grass with the guard's own sword already lying behind him. Two sound cues and one caption. No blood anywhere, nobody hurt, everybody losing. The dominant turn is the fight itself: trough, hat, one arm, and a boy. The four own the page together. The reader turns because four against five is going the four's way and the scar has not drawn yet. Rochefort is at the edge, sword still sheathed, watching.""",
    turn="Four beat five in one glorious bloodless picture: a guard in the trough, a hat pinned to the wall, a lunge into a tree, and a boy driving his man backward.",
    moments=[
        "One image, the whole page, about 100%, read top to bottom: at the top LEFT Porthos, enormous, lifting a red-cassocked guard clean off the ground and tipping him into the stone trough; at the top RIGHT Aramis, slim and unhurried, his blade pinning a guard's wide hat to the yellow wall through its brim while the bareheaded guard gapes beneath; in the middle band Athos, LEFT arm in the sling, stepping aside from a guard's lunge so that the guard runs headlong into the big tree; and across the lower centre, largest, the boy in ochre, hair flying, driving the fifth guard backward across the grass, the guard's own sword already lying in the grass behind the boy. Rochefort at the far right edge by the gap in the wall, in black, sword still sheathed, watching. No blood, no cut, no wound anywhere; every guard is losing and nobody is hurt.",
        "The trough sound cue sits beside the trough in large simple letters; the hat sound cue beside the pinned hat; the caption sits along the lower edge over the grass, tail-free. Nothing else is lettered.",
    ],
    locks=DART + " " + ATHOS_SLING + " " + PORTHOS + " " + ARAMIS + " " + ROCH + " " + THREE + " " + GUARDS,
    exclusions="Constance is absent. No blood, no wound, no blade in anyone; the swords of the guards are in the trough, in the grass, or in the air. Rochefort does not draw on this page. Exactly five guards. No lettering except the two sound cues and the caption: no laugh lines, no name plates.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/02-athos.png", "refs/approved/03-porthos.png", "refs/approved/04-aramis.png", "refs/approved/07-rochefort.png", "refs/approved/set-carmelite-field.png"],
    card=[
        ("Sound cues and caption transcription", "The two sound cues and the one caption read exactly from the 600 × 900 proof, once each, the trough cue by the trough and the hat cue by the pinned hat, the caption tail-free along the bottom, with no other text anywhere on the page. The run length of a repeated letter in a cue is nonblocking. " + C1_TAIL),
        ("The fight is not four clearly winning against five", "The eye must find, in one picture, a guard going into the trough, a hat pinned to the wall, a guard running into the tree, and the boy driving his man back, with the four unmistakably winning. If the picture reads as a general melee where the winners cannot be told, or as panels, the turn has not landed."),
        ("Bloodless fails", "Any blood, cut, stab, or wound on any figure is blocking. This page's whole promise is that nobody is hurt."),
        ("The four fail identity or collide", "Porthos huge and red-moustached at the trough, Aramis slim and blond at the wall, Athos tall and bearded with the LEFT sling at the tree, the boy clean-shaven in ochre in the centre; Rochefort scarred in black at the edge, sword sheathed. If any is missing or two merge, blocking."),
        ("Guard count or Rochefort's sword fails", "Exactly five guards in red cassocks; more or fewer is blocking. Rochefort drawn and fighting on this page is blocking."),
        ("Focal generation failure", "A duplicated Musketeer, a guard with two heads, gross anatomy on the boy's sword arm, or text across a face is blocking. Grass, wall, and background repetition are not."),
    ]),

15: dict(
    title="the third time, you stay",
    intent="""Dramatic. Rochefort's sword is out at last, and the boy turns from his beaten guard to face him: Meung, the inn yard, you laughed at my horse and took my letter; I took a letter, I don't remember a boy. Steel on steel, the boy fast, the man surprised, while behind them the guards are leaving through the gap in the wall, one wet, one hatless, one holding a pulled arm, and Porthos waves them off with his hat. Where did a farm boy learn that? From my father; where did you learn to run? Rochefort backs to the gap with his sword up, alone now: twice you've drawn on me, boy, twice is enough for one week; the third time, you stay. The dominant turn is the scar in front of the boy at last and the guards breaking. d'Artagnan owns the page; Rochefort loses ground on it. The reader turns because the scar is gone again but this time he had to run. Bloodless: nobody is touched.""",
    turn="The boy finally gets the scar's sword in front of his own, the guards break and run, and the scar backs out with a threat and a count.",
    moments=[
        "Panel one, about 30%, a strip: Rochefort on the RIGHT with his sword out at last, chin up; the boy on the LEFT turning from his beaten guard, blade up. Two balloons: the boy's accusation upper left, tail to his mouth; Rochefort's reply lower right, clearly after it, tail to his.",
        "Panel two, the dominant panel, about 45%, close and tall: the two blades crossed high, the boy on the LEFT fast and low, Rochefort on the RIGHT surprised, both faces clear; behind them, small and far, the guards going through the gap in the wall, one dripping wet, one bareheaded, one holding an arm, and Porthos waving them off with his enormous hat. The sound cue at the crossed blades. Rochefort's question upper right, the boy's answer lower left, tails to each mouth.",
        "Panel three, about 25%: Rochefort backing into the gap in the wall on the RIGHT, sword up, alone, the guards gone; the boy on the LEFT holding his ground. Rochefort's line upper right, tail to his mouth; the boy's line lower left, clearly after it, tail to his.",
    ],
    locks=DART + " " + ROCH + " " + PAIR_DR + " " + PORTHOS + " (small, in the middle distance, waving his plumed hat; silent on this page). " + GUARDS,
    exclusions="Athos and Aramis are present only as small figures far back if at all, silent; Constance is absent. No blood, no wound: the pulled arm is held, not bleeding; the wet guard is wet from the trough. No blade touches skin. No lettering on the wall; only the six spoken strings and the one sound cue.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/07-rochefort.png", "refs/approved/03-porthos.png", "refs/approved/set-carmelite-field.png"],
    card=[
        ("Dialogue transcription or ownership fails", "The six lines and the sound cue read exactly from the 600 × 900 proof, once each, in causal order; the boy's three lines hang from the boy and Rochefort's three from the scarred man in black; in each exchange the reply sits after the line it answers. Porthos and the guards carry no balloon. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the boy names Meung to the scar's face, they fence while the guards run, the scar backs out alone with a count. If the crossed blades of boy and scar are not the largest image the eye finds, or the guards are not visibly leaving, the turn has not landed."),
        ("Rochefort fails identity or collides with the boy", "One scar across a cheek from temple to mouth (which cheek is nonblocking), thin moustache, no beard, black, red feather; the boy clean-shaven in ochre. If either could be the other, or the scar is missing, blocking."),
        ("Bloodless fails", "No blood, no wound, no blade in anyone; a wet guard, a hatless guard, and a guard holding his arm are the whole damage."),
        ("Continuity fails", "The guards must be leaving through the gap, not fighting; Porthos must be waving a hat, not fencing; Rochefort ends the page alone at the gap. A guard still engaged or Rochefort still surrounded is blocking."),
        ("Focal generation failure", "A duplicated boy or scar-man, gross anatomy on the two sword hands at the cross, or a balloon over a face is blocking."),
    ]),

16: dict(
    title="four abreast",
    intent="""Dramatic. Toward evening, a Paris street: four abreast, filling it, walking back into the city, Porthos with one huge arm round the boy's neck, Aramis dusting his cuffs, Athos on the outside with his good hand on his pommel as he walks, blue cloaks making way. The boy is carried along in the middle, grinning, hair in his eyes. Porthos wants to know if everyone saw him put the guard in the trough; Aramis says all Paris saw it and pride goeth; Athos says pride went into the trough and the boy fought well. A step apart, Athos asks where the boy is sleeping; a horse and no money, so with the horse. Porthos spreads his arms: tonight the boy eats with them and Porthos is paying, well, Aramis is paying; in theory. The dominant turn is four abreast and the boy's name in the three men's mouths. The reader turns because he came to Paris with a letter and nobody to give it to, and is walking home with three friends.""",
    turn="Four men walk home abreast down a Paris street, and the boy who had a letter and nobody now has three friends and a dinner.",
    moments=[
        "Panel one, the dominant panel, about 55%, wide and close, the four filling the street and walking toward the viewer: from LEFT to RIGHT Porthos with his arm round the boy's neck, the boy in the middle grinning with his hair in his eyes, Aramis dusting his lace cuffs, Athos on the outside RIGHT with his good hand on his pommel, LEFT arm in the sling. Blue cloaks stepping aside behind them. Three balloons in reading order: Porthos's boast upper left over Porthos, tail to his mouth; Aramis's reply middle right of centre over Aramis, tail to his; Athos's line lower right over Athos, tail to his, clearly third.",
        "Panel two, about 25%: Athos and the boy a step apart from the other two, Athos on the RIGHT looking down, the boy on the LEFT. Athos's question upper right, the boy's answer lower left, tails to each mouth.",
        "Panel three, about 20%, as single-speaker beats: Porthos on the LEFT with his arms spread wide and his one long line, tail to his mouth; Aramis on the RIGHT touching his moustache with his two-word line, lower and after it, tail to his.",
    ],
    locks=DART + " " + ATHOS_SLING + " " + PORTHOS + " " + ARAMIS + " " + THREE + " Passing Musketeers: blue cassocks, clean-shaven or full-bearded, faceless where possible, silent.",
    exclusions="Rochefort and Constance are absent; no red feather, no scar, no red cassock in the street. No blood. All swords sheathed. No lettering on shops; only the seven spoken strings. No name plates.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/02-athos.png", "refs/approved/03-porthos.png", "refs/approved/04-aramis.png", "refs/approved/set-paris.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All seven lines read exactly from the 600 × 900 proof, once each, in causal order, each hanging by its tail from its owner: Porthos's two from the huge red-moustached man, Aramis's two from the slim blond, Athos's two from the tall bearded man in the sling, the boy's one from the boy. Passing Musketeers carry no balloon. " + C1_TAIL),
        ("The turn does not land", "The eye must find four men walking abreast toward the reader with the boy in the middle and an arm round his neck, before anything else. If the four are small, separated, or walking away, the turn has not landed."),
        ("The three Musketeers collide", "Porthos huge and red, Aramis slim and blond, Athos tall and dark with the LEFT sling. Any two merging is blocking."),
        ("d'Artagnan fails identity", "Clean-shaven, black hair in his eyes, ochre, no cloak, grinning in the middle. A moustache or a cassock on him is blocking."),
        ("Sling or bloodless fails", "The sling still on Athos's LEFT arm on this page; no blood or bandage on anyone else."),
        ("Focal generation failure", "A fifth companion, a duplicated Musketeer, gross anatomy on Porthos's arm round the boy, or a balloon across a face is blocking. Street crowd is not."),
    ]),
}
