MOV = 3
from mov1 import C1_TAIL, DART, ROCH, PAIR_DR
from mov2 import PORTHOS, ARAMIS, THREE

ATHOS = ("Athos, keyed to his sheet's default views: thirty, the tallest man in the book, long pale face, hooded level grey eyes, lines beside the mouth, dark hair straight to the shoulder, a short pointed dark beard and neat moustache, lean; "
         "blue cassock with the white cross over a black doublet, black hat with one white plume; NO sling (default state, pp 18–49); hands folded on the pommel of his grounded sword when still; the one man in any panel not moving.")
CONST = ("Constance, keyed to her sheet: twenty, small and quick, a head shorter than the boy, round face, soft chin, short straight nose, wide-set hazel eyes, dark brows, a scatter of freckles, dark brown curls pinned up under a white linen cap with strands escaping; "
         "slight, straight-backed, hands never idle; a plain dove-grey dress with white cuffs and a white apron whose bib carries one small embroidered gold crown; a ring of iron keys at her waist; a covered wicker basket on her arm (default state, pp 17–27); habitual gesture: chin lifted, looking up a stair.")
DART_SHIRT = ("d'Artagnan in shirt sleeves (pp 19–21): the same clean-shaven boy, black hair in his eyes, lean, in a plain white shirt with no doublet, brown breeches and boots, no hat, the too-long plain-hilted rapier in his hand; weight forward.")
CARD = ("The Cardinal, keyed to his sheet: forty-five, a thin ascetic man, long narrow hollow-cheeked face, high forehead, thin high-bridged nose, pale grey hooded eyes that do not blink, pale skin, grey hair cropped close under a red skullcap, a short pointed grey beard and thin grey moustache, both precise, narrow-shouldered, long-fingered; "
        "SEATED in a plain high-backed black chair in a robe and short cape of one saturated vermilion red with a small gold cross on a chain; a grey cat on his lap and one long hand stroking it, the hand never still. Never standing, never a sword, never a hat.")

PAGES = {
17: dict(
    title="two livres a week",
    intent="""Dramatic. A narrow street, a narrow house, a door at the foot of a steep wooden stair. Constance on the doorstep in grey and white, a small gold crown on her apron bib, keys at her waist, a basket on her arm, and the boy on the cobbles with the yellow horse and his hat in his hands. He says Athos sent him for the attic; two livres a week and a steep stair, can he pay it; not this week, next week he will be famous; everyone who comes to Paris says that. The stair, from the bottom: she has gone up ahead with the candle and turned to look down, he is at the foot looking up, and the crown on her apron catches the light; he asks about it; she dresses the Queen every morning and lets attics to Gascons who can't pay. The attic: a window, a bed, a table, a nail; he hangs his father's sword on the nail and promises to pay double; Constance, double is four livres, goodnight. The dominant turn is the attic, and the girl who dresses the Queen, and the boy finished the moment she looked down the stair. The reader turns because he is finished and she has already gone downstairs.""",
    turn="The boy rents an attic from a girl who dresses the Queen every morning, and is finished the moment she looks down the stair at him.",
    moments=[
        "Panel one, about 30%, a strip: a narrow street; the house door on the RIGHT at the foot of a steep wooden stair, Constance on the doorstep in grey and white, cap, keys, basket, the small gold crown on her apron; the boy on the LEFT on the cobbles holding the yellow horse's rein, hat in his hands. Four balloons as two single-speaker beats read left to right and down: the boy's introduction upper left, Constance's rent middle right, the boy's promise lower left, Constance's answer lowest right; each tail to its own mouth; no two level.",
        "Panel two, the dominant panel, about 45%, tall, seen from the foot of the stair looking up: Constance a few steps up on the RIGHT with a candle, turned to look down; the boy at the foot on the LEFT looking up; the gold crown on her apron bib catching the candlelight. The boy's line lower left by his mouth; Constance's reply upper right by hers.",
        "Panel three, about 25%: the attic, one window on the street, a bed, a table, a candle; the boy on the LEFT hanging the too-long sword on a nail in the beam; Constance on the RIGHT in the doorway. The boy's line upper left, tail to his mouth; Constance's last line lower right, tail to hers.",
    ],
    locks=DART + " " + CONST + " The yellow horse keyed to its plate, in panel one only.",
    exclusions="Athos, Porthos, Aramis, Rochefort, and the Cardinal are absent. No blood. The sword ends the page on the nail. The crown on the apron is a small embroidered emblem, not a jewel, and carries no letters. No lettering on the house, the door, or the stair; only the eight spoken strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/05-constance.png", "refs/approved/obj-horse.png", "refs/approved/set-house.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All eight lines read exactly from the 600 × 900 proof, once each, in causal order; the boy's four hang from the boy and Constance's four from the girl in the cap; in the four-line doorstep exchange each reply sits after the line it answers. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the boy asks for the attic and cannot pay, she looks down the stair at him with a crown on her apron, he hangs his sword on the nail and she says goodnight. If the stair with her looking down and him looking up is not the largest image the eye finds, the turn has not landed."),
        ("Constance fails identity", "Small, round-faced, freckled, dark curls under a white cap, grey dress, white apron with a small gold crown, keys, basket. Finery, a crown on her head, jewels, or blonde hair is blocking."),
        ("d'Artagnan fails identity", "Clean-shaven, black-haired, ochre, no cloak, the too-long sword. A moustache or cassock is blocking."),
        ("Object state fails", "The sword must end on the nail in the attic; the apron crown must read as a small emblem; the horse in panel one must be yellow. Exact attic furniture is nonblocking."),
        ("Focal generation failure", "A duplicated Constance or boy, a third figure in the house, gross anatomy on the hand with the candle or the hand at the nail, or a balloon across a face is blocking."),
    ]),

18: dict(
    title="weeks",
    intent="""Illustrated prose, two locations because the weeks are the turn: the Carmelite field at dawn, and the stair. The dominant image is the field: Athos, the sling gone, teaching the boy with blades crossed and his boot nudging the boy's back foot into place, neither of them talking. The smaller image is the stair: Constance at the bottom with her basket and her keys, looking up; the boy at the top, looking down. The prose carries the four inseparable, Porthos's stories, Aramis's Latin, Athos's offer to walk him through the gate and the boy's refusal, and every evening the look up the stair that neither of them mentions. The dominant turn is weeks going by and the girl looking up the stair every evening. The four own the mornings; Constance owns the evenings. The reader turns because every evening she looks up the stair, and this is the last evening on which nothing happens.""",
    turn="Weeks go by: dawn lessons with Athos, dinners with the four, and every evening a girl looking up a stair at a boy who is there.",
    moments=[
        "Panel one, the dominant image, about 65%, close and tall: dawn on the Carmelite meadow by the yellow wall, Athos on the RIGHT with NO sling, tall and still, his blade crossed with the boy's, his boot nudging the boy's back foot into place; the boy on the LEFT, hatless, concentrating. Neither speaks. Pale early light, dew.",
        "Panel two, about 35%: the steep stair seen from the side or from the top: Constance at the bottom with her basket and her keys, chin lifted, looking up; the boy at the top of the stair looking down. Warm evening lamplight.",
        "The prose field sits over the pale field and sky in panel one, a matte parchment field across most of the width, never over the two fencers or the stair. Two paragraphs. No other lettering.",
    ],
    locks=DART + " " + ATHOS + " " + CONST + " Athos has no sling on this page or any page after.",
    exclusions="Porthos and Aramis are named in the prose but are not drawn on this page; Rochefort and the Cardinal are absent. No blood; the fencing is a lesson. No sling on Athos. No lettering except the one prose field.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/02-athos.png", "refs/approved/05-constance.png", "refs/approved/set-carmelite-field.png", "refs/approved/set-house.png"],
    card=[
        ("Prose transcription", "The prose field reads exactly, both paragraphs in order, once, from the 600 × 900 proof, over plain ground and never over the fencers or the stair, with no other text on the page. " + C1_TAIL),
        ("The lesson does not own the page", "The eye must find first the tall man teaching the boy with crossed blades at dawn, then the small warm stair with the girl looking up. If the stair competes or the page reads as a comic strip, the turn has not landed."),
        ("Athos fails identity or wears the sling", "Tall, dark shoulder-length hair, pointed beard, blue cassock, white plume, both arms free. A sling, a scar, or black clothes is blocking."),
        ("Constance or d'Artagnan fails identity", "The girl small in grey and white with cap, keys, and basket looking up; the boy clean-shaven and black-haired at the top. Blocking if either is contradicted."),
        ("Focal generation failure", "A duplicated fencer, a second girl, gross anatomy on the crossed sword hands, or the prose field over a face is blocking."),
    ]),

19: dict(
    title="out of the window",
    intent="""Dramatic, two locations because the jump is the turn: the attic window, and the street below. Night, rain. Above, the boy at the open window in his shirt, cleaning the sword. Below, a cart, a lantern on a bracket, and four men in plain cloaks closing on Constance at her own door, one hand reaching for her mouth, the basket falling; she shouts for help and gets half his name out. He goes out of the window, not the stair: one hand on the sill, the sword in the other, dropping two floors through the rain onto the cart roof with a bang. He lands between the men and the door, sword out, hair in his eyes, and across the street in a dark doorway a fifth figure in black with a red feather stands with his arms folded and does not move. The dominant turn is the men taking Constance and the boy going out of the window. The reader turns because it is one boy, four men, one lantern, and rain.""",
    turn="Men seize Constance at her door in the rain, and the boy comes out of the attic window two floors up rather than down the stair.",
    moments=[
        "Panel one, about 25%, a tall strip that holds both locations: at the top, the boy in a white shirt at the open attic window, sword and cloth in his hands, looking down; at the bottom, in the rain-lit street, a cart, a lantern on a bracket, and four men in plain dark cloaks closing on Constance at the house door on the RIGHT, one hand reaching toward her mouth, her basket falling. Constance's cry beside her, tail to her mouth. The men are silent.",
        "Panel two, the dominant panel, about 50%, tall: the boy going out of the window, one hand on the sill, the sword in the other, dropping two floors through the rain toward the roof of the cart, the lantern's light catching him. His one-word shout beside him, tail to his mouth; the sound cue at the cart roof below, large.",
        "Panel three, about 25%: the boy landed, on the ground between the four men (LEFT) and Constance at the door (RIGHT), sword out, hair in his eyes, the men turning to him. Across the street behind them, in a dark doorway, a fifth figure all in black with one red feather, arms folded, not moving; his scar catches the lantern. The boy's line beside him, tail to his mouth.",
    ],
    locks=DART_SHIRT + " " + CONST + " " + ROCH + " (in the doorway across the street, arms folded, still; silent on this page). The four men: plain dark cloaks and hats, faces generic, no feather, no scar, no cassock; silent.",
    exclusions="Athos, Porthos, Aramis, and the Cardinal are absent. No blood; nobody is struck on this page. The boy wears no doublet and no hat. Rochefort does not draw and does not move. The lantern is still lit and on its bracket on this page. No lettering on the house or the cart; only the three spoken strings and the one sound cue.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/05-constance.png", "refs/approved/07-rochefort.png", "refs/approved/set-house.png"],
    card=[
        ("Dialogue transcription or ownership fails", "Constance's cut-off cry, the boy's shout, the sound cue, and the boy's challenge read exactly from the 600 × 900 proof, once each, in causal order; the cry hangs from the girl at the door, the shout and the challenge from the boy; the four men and the man in the doorway carry no balloon. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: men seize the girl below while the boy watches from the window, the boy drops out of the window onto the cart, he lands between the men and the door. If the boy in mid-drop is not the largest image the eye finds, the turn has not landed."),
        ("Rochefort is missing or wrong", "A figure in black with a red feather and a scar must stand in a doorway across the street with folded arms in the last panel, not fighting. A missing watcher, or the watcher drawing a sword, is blocking."),
        ("Constance or d'Artagnan fails identity", "The girl small in grey with the white cap and falling basket; the boy clean-shaven, black-haired, in a white shirt with no doublet. A doublet or hat on the boy here, or a bearded boy, is blocking."),
        ("Bloodless or count fails", "Exactly four attackers; no blood; nobody struck. Five attackers or a wounded figure is blocking."),
        ("Focal generation failure", "A duplicated boy at window and ground in the same panel, gross anatomy on the hand on the sill, or a balloon across a face is blocking. Rain texture is not."),
    ]),

20: dict(
    title="the lantern in the puddle",
    intent="""Spectacle. The fight in the rain in one picture: the boy in his white shirt a blur in the middle; one man already sitting in the puddle; one running; one losing his sword into the air; the lantern knocked off its bracket and falling, still lit; Constance flat against her own door with the basket held in front of her; and across the street, in the doorway, the black figure with the red feather, arms folded, watching. One sound for the lantern, one caption. The dominant turn is one boy against four men, one lantern, and rain, and the lantern going out. The boy owns the page; the watcher in the doorway owns its edge. The reader turns because the lantern is out and the man across the street has not moved. Bloodless: men fall, run, and lose swords; nobody is cut.""",
    turn="One boy in a white shirt beats four men in the rain, and the lantern goes into the puddle so that only he can see.",
    moments=[
        "One image, the whole page, about 100%: the narrow street at night in rain, seen a little from above. In the centre the boy in a white shirt mid-lunge, a blur of motion, sword out; to the LEFT one attacker sitting down hard in the puddle; behind, one running away up the street; to the RIGHT one attacker's sword leaving his hand into the air; the fourth turning to flee. The lantern, knocked from its bracket, falling through the air still lit, its light streaking. Constance flat against the house door on the RIGHT, the basket held in front of her. Across the street, upper LEFT, in a dark doorway, Rochefort in black with the red feather, arms folded, watching, the scar catching the last of the lantern light. No blood, no cut, nobody wounded.",
        "The sound cue sits beside the falling lantern in large simple letters. The caption sits along the lower edge over the wet cobbles, tail-free. Nothing else is lettered.",
    ],
    locks=DART_SHIRT + " " + CONST + " " + ROCH + " (arms folded in the doorway, silent, not fighting). The four attackers: plain dark cloaks, faces generic, no feather, no scar, no cassock.",
    exclusions="Athos, Porthos, Aramis, and the Cardinal are absent. No blood, no wound. Rochefort does not draw and does not move. Exactly four attackers, all losing. The boy wears no doublet and no hat. No lettering except the sound cue and the caption.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/05-constance.png", "refs/approved/07-rochefort.png", "refs/approved/set-house.png"],
    card=[
        ("Sound cue and caption transcription", "The sound cue by the falling lantern and the one caption along the bottom read exactly from the 600 × 900 proof, once each, with no other text on the page. The run length of the cue's letters is nonblocking. " + C1_TAIL),
        ("The fight is not one boy beating four in the rain", "The eye must find one boy in a white shirt in the middle of four men who are falling, running, and losing their swords, a falling lantern, a girl against a door, and a still watcher across the street. If it reads as an even brawl, as panels, or the boy is one of a crowd, the turn has not landed."),
        ("Bloodless fails", "Any blood, cut, or wound on anyone is blocking."),
        ("Rochefort or Constance fails", "The watcher in black with the red feather and scar, arms folded, must be present and still; Constance must be at the door with the basket. A watcher who fights, or a missing girl, is blocking."),
        ("Count or state fails", "Exactly four attackers; the lantern falling and still lit; the boy in a shirt with no doublet. Five attackers or a lantern still on its bracket is blocking."),
        ("Focal generation failure", "A duplicated boy, gross anatomy on the boy's sword arm, or text colliding with a figure is blocking. Rain and cobble texture are not."),
    ]),

21: dict(
    title="she only carries it",
    intent="""Dramatic. The men are gone. Rain. The boy, breathing hard, sword lowered; Rochefort stepping out of the doorway into what light there is, hands empty, scar and red feather. Three times you've drawn on me, Gascon, and I'm still not staying; I said the third time you'd stay, draw; not in the rain and not for a seamstress, she isn't what I was sent for, she only carries it. He walks away up the street, unhurried, and the boy shouts after him: carries what? The doorway: Constance shaking, picking up the basket, the boy beside her wet through. What did he mean, what does she carry? The Queen's letters, she carries them for her, where and to whom she can't tell, it isn't hers to tell. Then don't tell me; I'll be upstairs, tonight and every night, until they stop coming. They won't stop. Then neither will I. The dominant turn is Rochefort's one word too many, the letters, and the boy staying anyway. The reader turns because the men were sent for the Queen's letters and the girl will not say where they go.""",
    turn="The scar declines to fight in the rain, lets slip that the girl only carries something, and the boy learns it is the Queen's letters and says he will be upstairs every night.",
    moments=[
        "Panel one, about 30%, a strip: the empty rain-dark street; the boy on the LEFT breathing hard, sword lowered, wet through; Rochefort on the RIGHT stepping out of the doorway, hands empty and open, scar toward the viewer, red feather dark with rain. Three balloons A–B–A: Rochefort's count upper right, the boy's demand middle left, Rochefort's long refusal lower right, tails to each mouth.",
        "Panel two, about 20%, a strip: Rochefort walking away up the street, unhurried, back to the viewer, the red feather the last colour; the boy small on the LEFT shouting after him. The boy's two-word line beside him, tail to his mouth.",
        "Panel three, the dominant panel, about 50%, close and tall, the house doorway: Constance on the RIGHT, shaking, stooping for the basket; the boy on the LEFT beside her, wet through, sword hanging. Five balloons as single-speaker beats stacked and read down, alternating sides: the boy's question upper left, Constance's answer upper right below it, the boy's promise middle left, Constance's three words lower right, the boy's last line lowest left; each tail to its own mouth; no two level.",
    ],
    locks=DART_SHIRT + " " + CONST + " " + ROCH + " " + PAIR_DR,
    exclusions="Athos, Porthos, Aramis, and the Cardinal are absent; the four attackers are gone from the street. No blood. Rochefort's sword stays sheathed and his hands stay empty. The lantern is out and in the puddle, unfocal. No lettering on the house; only the nine spoken strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/05-constance.png", "refs/approved/07-rochefort.png", "refs/approved/set-house.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All nine lines read exactly from the 600 × 900 proof, once each, in causal order; Rochefort's two from the scarred man in black, the boy's five from the boy, Constance's two from the girl at the door; in the doorway exchange each reply sits after the line it answers and alternates sides. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the scar refuses to fight and says she only carries it, walks away, and the girl tells the boy it is the Queen's letters while he promises to stay. If the doorway exchange is not the largest image the eye finds, the turn has not landed."),
        ("Rochefort fails identity or draws", "One scar across a cheek from temple to mouth (which cheek is nonblocking), thin moustache, black, red feather, hands empty, sword sheathed. A drawn sword, a beard, or a missing scar is blocking."),
        ("Constance or d'Artagnan fails identity", "The girl small in grey with the cap, shaking, with the basket; the boy clean-shaven in a white shirt, no doublet. Blocking if contradicted."),
        ("Bloodless or continuity fails", "No blood on anyone; the attackers gone; the lantern out. An attacker still present is blocking."),
        ("Focal generation failure", "A duplicated Rochefort, a third figure in the doorway, gross anatomy on the hands at the basket, or a balloon across a face is blocking."),
    ]),

22: dict(
    title="only two",
    intent="""Dramatic. A red room with one candle and no window. The Cardinal in a chair: a thin man in a red robe and red skullcap, a short pointed grey beard, a grey cat on his lap, one long hand stroking it; on the black desk before him a folded cream letter with a broken red seal, the letter from Meung. Rochefort standing, wet from the rain, hat in his hands. A caption names the Cardinal and says the scar and every red cloak answer to him. The girl got away, a boy stopped them, the Gascon; the Cardinal has the father's letter, does not need tonight's, has read the Queen's letters for a year and knows what she sent: twelve diamond studs, the King's gift, on the Duke of Buckingham's shoulder; go to London, bring two, only two. Why not all twelve? He would miss twelve; nobody counts to two. And then? And then the King will give a ball. The dominant turn is the order: two diamonds, only two, and a ball. The Cardinal owns the page without raising his voice. The reader turns because he knows what a ball has to do with it and you do not yet. This is the heaviest page in the book: nine strings; lanes before faces.""",
    turn="In a red room, a calm man with a cat sends the scar to London to cut two diamonds off a duke's shoulder, because the King is going to give a ball.",
    moments=[
        "Panel one, the dominant panel, about 50%, close and tall, and the balloon lanes reserved before the faces are placed: the red room, red hangings, a black desk with a single candle, no window. The Cardinal on the RIGHT seated in a plain high-backed black chair, red robe and skullcap, grey pointed beard, a grey cat on his lap under one long stroking hand; on the desk in front of him, plainly visible, a folded cream letter with a BROKEN red wax seal. Rochefort on the LEFT standing, wet, hat in both hands, scar toward the viewer. The caption upper left over the red hangings, tail-free. Rochefort's report upper left below the caption, tail to his mouth; the Cardinal's long reply upper right, clearly after it, tail to his mouth.",
        "Panel two, about 25%: close on the Cardinal's face, pale unblinking hooded eyes, and below it the hand on the cat. Two balloons stacked on his side, the studs line first, the London order below it, both tails to his mouth.",
        "Panel three, about 25%, as single-speaker beats: Rochefort at the door on the LEFT, turned back; the Cardinal in his chair on the RIGHT. Four balloons alternating and descending: Rochefort's question upper left, the Cardinal's answer upper right below it, Rochefort's two words middle left, the Cardinal's last line lowest right; each tail to its own mouth; no two level.",
    ],
    locks=CARD + " " + ROCH + " The risky pair by type is the Cardinal against the absent Athos: keep the Cardinal grey, cropped under a cap, seated, and in red so he can never be taken for the tall dark standing Musketeer. The cat: a plain grey cat, calm, on the lap. The letter keyed to the letters plate, broken-seal state.",
    exclusions="d'Artagnan, Constance, Athos, Porthos, Aramis, and Buckingham are absent. The Cardinal never stands on this page and never raises a hand. No sword is drawn. The letter on the desk shows a broken seal and no legible words; the Queen's letters are not on the desk. No window, no daylight. No lettering on maps or papers; only the caption and the eight spoken strings.",
    inputs=["refs/approved/06-cardinal.png", "refs/approved/07-rochefort.png", "refs/approved/obj-letters-pass.png", "refs/approved/set-cardinal-study.png"],
    card=[
        ("Dialogue transcription or ownership fails", "The caption and all eight lines read exactly from the 600 × 900 proof, once each, in causal order; the Cardinal's five hang from the seated man in red and Rochefort's three from the standing man in black; each reply sits after the line it answers; the caption is tail-free; nothing on the desk or maps is legible. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the scar reports failure to a seated man in red, the man says what the Queen sent and orders two diamonds only, and answers the last question with a ball. If the seated red figure with the cat and the wet standing man is not the largest image the eye finds, the turn has not landed."),
        ("The Cardinal fails identity", "Thin, grey pointed beard, red robe and red skullcap, seated with a grey cat under his hand, never standing. A dark beard, hair to the shoulder, standing, or a sword is blocking; the cat missing is blocking."),
        ("Rochefort fails identity or collides with the Cardinal", "One scar across a cheek from temple to mouth (which cheek is nonblocking), thin black moustache, black clothes, hat in hand, standing and wet. If he could be taken for the man in the chair, blocking."),
        ("The letter state fails", "A folded cream letter with a broken red seal must lie plainly on the desk; a sealed letter, a blue-sealed letter, or legible writing is blocking. Exact position on the desk is nonblocking."),
        ("Focal generation failure", "A duplicated Cardinal, two cats, a window or daylight in the red room, gross anatomy on the stroking hand, or a balloon across either face is blocking."),
    ]),
}
