MOV = 7
from mov1 import C1_TAIL, DART, ROCH
from mov2 import PORTHOS, ARAMIS, THREE
from mov3 import ATHOS, CARD
from mov5 import DART_ROAD
from mov6 import MUD

CONST_BALL = ("Constance at the ball, keyed to her sheet's view d: the same small freckled girl, dark curls under the white cap, the dove-grey dress with the apron OFF and a plain white collar in its place, no basket, no keys (ball state, pp 41–46).")
ROCH_SLING = ("Rochefort at the ball, keyed to his sheet: hat on with the red feather, the scar from the left temple to the mouth, thin moustache, all black, and his RIGHT arm in a white sling (sling state, pp 42–46); sword sheathed.")
CARD_BALL = ("The Cardinal at the ball: as on his sheet, thin, grey pointed beard, red robe and red skullcap, SEATED in a plain chair set beside the dais, no cat; on the arm of the chair under his hand a folded cream letter with a broken red seal. He stands once only, on page 45.")
QUEEN = ("The Queen is scenery: a figure in white and silver with a small crown, seen from behind or at a distance, face never close, with a blaze of diamonds in two rows on her LEFT shoulder drawn large and bright as one cluster; no balloon. The King is scenery: a crowned figure seated on the dais, no face, no balloon. The court: gold and silver silk, faceless, nobody in red, ochre, or a black doublet.")
RING = "The Queen's ring keyed to the casket plate: a gold ring with one dark stone."

PAGES = {
41: dict(
    title="the kitchen door",
    intent="""Dramatic. A service door at the back of the Louvre, torchlight, kitchen noise behind it. Constance in the doorway in her grey with the apron off; the boy coming up out of the dark with mud to the waist and the closed casket under his arm. You're here; every night since you left she has stood in this door; is it—; twelve, count them. The casket open between them in torchlight, her lips moving over the double row, his eyes on her face and not on the box: ten, eleven, twelve, twelve; two of them are new, the scar cut two out at the Duke's ball and the Duke had two made and nobody can tell which, not even the Duke could. The box shut against her chest, she is already turning up the stair and he has sat down on the bottom step: she's dressing, she has ten minutes, go round to the front doors and stand where she can see you; where the Cardinal can see me; yes, that too. The dominant turn is the box changing hands and the count to twelve. Constance owns the count; the boy owns the watching. The reader turns because the box has changed hands and there are ten minutes.""",
    turn="At the kitchen door of the Louvre the boy puts the box into Constance's hands, she counts to twelve, and she sends him round to stand where the Cardinal can see him.",
    moments=[
        "Panel one, about 30%: a torchlit service door at the back of the palace, kitchen steam and copper behind it. Constance on the RIGHT in the doorway, grey dress, apron off, white collar, cap; the boy on the LEFT coming up out of the dark with mud to the waist and the closed casket under his arm. Constance's line upper right, tail to her mouth; the boy's answer lower left, after it, tail to his.",
        "Panel two, the dominant panel, about 50%, close and tall: the casket open between them in the torchlight, her face lit over it with her lips moving, the double row of studs bright; his face on the LEFT turned to hers, not to the box. Exactly two hands on the box, hers. Three balloons: Constance's count upper right, tail to her mouth; the boy's long line middle left, after it, tail to his; his short line below it on his side.",
        "Panel three, about 20%: Constance on the RIGHT with the box shut against her chest, already turning up a stone stair into the light; the boy on the LEFT sat down on the bottom step. Three balloons A–B–A: Constance's instruction upper right, the boy's line middle left, Constance's three words lowest right, tails to each mouth, none level.",
    ],
    locks=DART_ROAD + " " + MUD + " " + CONST_BALL + " The casket keyed to its plate, twelve studs, no empty slot; the reader is never asked to count. Kitchen figures, if any: faceless, silent.",
    exclusions="Athos, Porthos, Aramis, Rochefort, the Cardinal, and Buckingham are absent. The Queen does not appear. Constance wears no apron and carries no basket. No empty slot in the casket on this page. No blood. No lettering on the door or the copper; only the eight spoken strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/05-constance.png", "refs/approved/obj-casket-pouch-ring.png", "refs/approved/set-louvre.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All eight lines read exactly from the 600 × 900 proof, once each, in causal order; Constance's four hang from the girl in the cap and the boy's four from the muddy boy; each reply sits after the line it answers. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: she is in the door and he arrives with the box, she counts twelve while he watches her face, she takes the box up the stair and sends him to the front. If her face over the open box with the boy looking at her is not the largest image the eye finds, the turn has not landed."),
        ("Constance fails identity or state", "The small freckled girl in grey with the white cap, apron off and a white collar, no basket. An apron, a basket, or finery is blocking."),
        ("d'Artagnan fails identity", "Clean-shaven, black-haired, ochre with mud to the waist. A clean or moustached boy is blocking."),
        ("The casket state fails", "The casket must be open in the second panel with a full double row and no empty slot, and shut in the third. An empty slot here is blocking."),
        ("Focal generation failure", "Exactly two hands on the open box; a third figure in the doorway, a duplicated Constance, or a balloon across a face is blocking."),
    ]),

42: dict(
    title="ten is ten",
    intent="""Dramatic. A hall of gold and a thousand candles, a court in silk, a dais with two thrones and a crowned figure on one; beside the dais one column of red: the Cardinal seated in a chair set there for him, and on the arm of the chair under his hand a folded cream letter with a broken red seal, as if he had been reading it while he waited; behind the chair Rochefort with his right arm in a white sling; above, in the gallery, Constance in grey without the apron, both hands on the rail, watching the long shut doors. And the boy, Eminence, the Gascon reached the boat; a boy reached a boat, he has the father's letter and knows what he is, the Duke has ten, ten is ten. The Cardinal's long hand draws a small pouch half out of his red sleeve and pushes it back: she will come in wearing ten because ten is what she has, and he will go to her with the two she lost in front of everyone and the King will count. The gallery: Constance's hands white on the rail, the doors shut, a herald's staff rising: come on, come on, come on. The dominant turn is the pouch in the sleeve, the sling, and a plan said aloud in the wrong room. The reader turns because the doors are opening and the Cardinal has two diamonds in his sleeve.""",
    turn="Beside the dais the Cardinal, with the two diamonds in his sleeve and the boy's letter under his hand, explains to a sling-armed Rochefort how the Queen will wear ten, while Constance in the gallery watches the doors.",
    moments=[
        "Panel one, the dominant panel, about 45%, wide and tall: the ballroom in gold and candlelight, a court in silk seen from the side, the dais at the far end with a crowned faceless figure on one throne and the other empty; beside the dais, near the viewer, one column of red: the Cardinal seated in a plain chair, a folded cream letter with a broken red seal on the chair's arm under his hand; behind the chair Rochefort, hat and red feather, RIGHT arm in a white sling; high above, in the gallery, small, Constance in grey with a white collar, hands on the rail. Rochefort's question upper right beside him, tail to his mouth; the Cardinal's long answer below it on his side, tail to his mouth.",
        "Panel two, about 25%, close: the Cardinal's long hand drawing a small leather pouch half out of the red sleeve and pushing it back; his face above, calm. Two balloons stacked on his side, both tails to his mouth, the ten line first.",
        "Panel three, about 30%: the gallery, Constance's hands white on the rail on the RIGHT, her face lit from below; beneath her, the long doors all shut and a herald's staff rising to strike the floor. Constance's line beside her, tail to her mouth.",
    ],
    locks=CARD_BALL + " " + ROCH_SLING + " " + CONST_BALL + " " + QUEEN + " The risky pair by type is the Cardinal against the absent Athos; keep him grey, capped, seated, and red. The pouch keyed to the casket plate: a small drawstring leather pouch, closed.",
    exclusions="d'Artagnan, Athos, Porthos, Aramis, and Buckingham are absent; the Queen has not entered; the doors are shut. The Cardinal is seated throughout and has no cat. The letter on the chair arm has a broken seal and no legible writing. The pouch stays closed; no diamonds are visible on this page. No blood. No lettering on the dais or banners; only the five spoken strings.",
    inputs=["refs/approved/06-cardinal.png", "refs/approved/07-rochefort.png", "refs/approved/05-constance.png", "refs/approved/obj-letters-pass.png", "refs/approved/obj-casket-pouch-ring.png", "refs/approved/set-louvre.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All five lines read exactly from the 600 × 900 proof, once each, in causal order; the Cardinal's three hang from the seated man in red, Rochefort's one from the slung man in black behind him, Constance's one from the girl in the gallery; the King and the court carry no balloon. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the Cardinal dismisses the boy with the letter under his hand, shows and hides a pouch in his sleeve while saying the Queen will wear ten, and in the gallery Constance waits on the doors. If the red seated figure beside the dais with the slung man behind is not the largest image the eye finds, the turn has not landed."),
        ("The Cardinal fails identity or stands", "Thin, grey pointed beard, red robe and skullcap, seated, no cat, the cream letter with the broken seal on the chair arm. Standing, dark-haired, or a sword is blocking."),
        ("Rochefort fails identity or the sling is wrong", "One cheek scar, thin moustache, black, red feather, RIGHT arm in a white sling. The left arm slung or no sling is blocking."),
        ("Constance or the Queen fails", "Constance in the gallery in grey with a white collar and no apron; the Queen absent and the doors shut. The Queen already in the hall is blocking."),
        ("Focal generation failure", "A duplicated Cardinal, a cat, an open pouch with visible stones, gross anatomy on the hand at the sleeve, or a balloon across a face is blocking. Crowd repetition and candle flare are not."),
    ]),

43: dict(
    title="the Queen came in",
    intent="""Spectacle. The Queen enters: a figure in white and silver seen from the gallery over Constance's shoulder, from behind and above, walking the length of the hall through a court that bows like wheat, and on her left shoulder a blaze of diamonds in two rows, drawn large and bright. At the far end, small, the red chair, and the man in it leaning forward. One caption. The dominant turn is the Queen entering wearing twelve. The Queen owns the page without a face. The reader turns because the Cardinal is counting. The diamonds are one bright cluster, never a counting puzzle.""",
    turn="Seen over Constance's shoulder from the gallery, the Queen walks the length of the hall with a blaze of diamonds on her shoulder, and far away a red figure leans forward.",
    moments=[
        "One image, the whole page, about 100%, seen from the gallery over Constance's shoulder and cap in the near foreground at the lower LEFT, from behind and above: the Queen below, a figure in white and silver with a small crown, seen from behind, walking away down the length of the gold hall between two banks of court bowing like wheat in wind; on her LEFT shoulder a blaze of diamonds in two rows, drawn large and bright as one cluster, the brightest thing on the page. At the far end, small, the dais with the crowned faceless figure, and beside it the red chair with the man in red leaning forward in it and a black figure with a white sling behind.",
        "The caption sits along the lower edge over the polished floor, tail-free. Nothing else is lettered.",
    ],
    locks=CONST_BALL + " (near foreground, from behind). " + QUEEN + " " + CARD_BALL + " (small, far). " + ROCH_SLING + " (small, far).",
    exclusions="d'Artagnan, Athos, Porthos, Aramis, and Buckingham are absent. The Queen's face is never seen; she is from behind. The Cardinal stays seated. No blood. No lettering except the caption. The diamonds are a bright cluster; no attempt to make each stone countable.",
    inputs=["refs/approved/05-constance.png", "refs/approved/06-cardinal.png", "refs/approved/07-rochefort.png", "refs/approved/set-louvre.png"],
    card=[
        ("Caption transcription", "The one caption reads exactly from the 600 × 900 proof, once, tail-free, with no other text on the page. " + C1_TAIL),
        ("The entrance does not own the page", "The eye must find, from above and behind, a woman in white walking down a golden hall through a bowing court with a blaze of diamonds on her left shoulder, with a girl's shoulder and cap in the foreground and a small red figure at the far end. If the Queen's face is shown close, or the diamonds are not the brightest thing, or the page reads as panels, the turn has not landed."),
        ("The Queen fails as scenery", "A close face, a balloon, or a Queen in any colour but white and silver is blocking; the diamonds must be on her LEFT shoulder."),
        ("The far figures fail", "The red figure at the far end must be seated and leaning forward with a slung black figure behind; a standing Cardinal here is blocking."),
        ("Focal generation failure", "A duplicated Queen, the diamonds rendered as a countable row of separate pegs, or text colliding with a figure is blocking. Court repetition is not."),
    ]),

44: dict(
    title="twelve",
    intent="""Dramatic. The Cardinal's face, close, his lips moving, his hand on the pouch in his sleeve stopped: ten, eleven, twelve; twelve. Rochefort bending to his ear, sweating: he cut two, he swears it, they are in the sleeve; then someone made two. Then, from beside the red chair looking down the hall: the Queen has reached the dais and the crowned figure's hand is taking hers, the twelve blazing on her shoulder, the court coming up out of its bow like wheat standing after wind; in the near foreground, large, the Cardinal's long hand pushing the pouch all the way back into the red sleeve; and a small inset of Constance in the gallery with both hands coming off the rail. One caption. The dominant turn is the count failing and the pouch going back into the sleeve as the King takes the Queen's hand. The Cardinal owns the count; the room owns the consequence. The reader turns because the trick has failed and the man who never stands is getting up.""",
    turn="The Cardinal counts twelve, twice, and pushes the two diamonds back into his sleeve as the King takes the Queen's hand and the court comes up out of its bow.",
    moments=[
        "Panel one, about 25%, close: the Cardinal's face, pale hooded eyes fixed down the hall, his lips moving; below his face, his hand on the pouch at the sleeve, stopped. Two balloons stacked on his side, the count first, the single word below it, both tails to his mouth.",
        "Panel two, about 25%: Rochefort on the LEFT bending to the Cardinal's ear, sweating, the white sling on his right arm; the Cardinal on the RIGHT unmoving. Rochefort's line upper left, tail to his mouth; the Cardinal's four words lower right, after it, tail to his.",
        "Panel three, the dominant panel, about 50%, wide and tall, from beside the red chair looking down the hall: in the near foreground, large, the Cardinal's long red-sleeved hand pushing a small leather pouch all the way back into the sleeve; beyond it the Queen from behind reaching the dais with the diamonds blazing on her left shoulder and the crowned faceless figure's hand taking hers; the court rising out of its bow. A small inset in one corner: Constance in the gallery, both hands lifting off the rail. The caption along the lower edge over the polished floor, tail-free.",
    ],
    locks=CARD_BALL + " " + ROCH_SLING + " " + CONST_BALL + " (inset). " + QUEEN + " The pouch keyed to the casket plate, closed, going into the sleeve.",
    exclusions="d'Artagnan, Athos, Porthos, Aramis, and Buckingham are absent; the boy is not yet in the doorway on this page. The Cardinal remains seated on every panel. The Queen's face is never close. No diamonds spill from the pouch. No blood. No lettering except the four spoken strings and the caption.",
    inputs=["refs/approved/06-cardinal.png", "refs/approved/07-rochefort.png", "refs/approved/05-constance.png", "refs/approved/obj-casket-pouch-ring.png", "refs/approved/set-louvre.png"],
    card=[
        ("Dialogue transcription or ownership fails", "The four lines and the caption read exactly from the 600 × 900 proof, once each, in causal order; the Cardinal's three hang from the seated man in red, Rochefort's one from the slung man at his ear; the caption is tail-free; the King, Queen, and court carry no balloon. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the Cardinal counts to twelve, Rochefort swears he cut two and the Cardinal says someone made two, and the pouch goes back into the sleeve as the King takes the Queen's hand. If the hand pushing the pouch into the sleeve with the Queen reaching the dais beyond is not the largest image the eye finds, the turn has not landed."),
        ("The Cardinal fails identity or stands", "Thin, grey pointed beard, red robe and skullcap, seated on every panel; standing here is blocking because the next page is the only time he stands."),
        ("Rochefort fails identity or the sling is wrong", "One cheek scar, thin moustache, black, red feather, RIGHT arm in a white sling, bending to the ear. Blocking if contradicted."),
        ("The consequence fails", "The Queen from behind at the dais with the diamonds on her left shoulder and a crowned figure taking her hand, the court rising, and Constance's hands leaving the rail in an inset. A Queen still walking, or no inset, is blocking. The Queen's face close is blocking."),
        ("Focal generation failure", "A duplicated Cardinal, stones spilling from the pouch, gross anatomy on the hand at the sleeve, or a balloon across a face is blocking."),
    ]),

45: dict(
    title="d'Artagnan",
    intent="""Dramatic. The Cardinal standing, for the only time in the book, and turning toward the long doors; in the last of them, a boy with mud to the waist, hat in hand, hair in his eyes, looking straight back at him across the whole ballroom. Who is that boy? The Gascon, from Meung. The Cardinal's hand takes the folded cream letter with the broken red seal from the arm of the chair beside him, unfolds it, and reads the name at the bottom: ah, the letter, a father asking a favour for a son; d'Artagnan. The dominant turn is the Cardinal standing, the boy in the doorway, and the name read off the stolen letter. The Cardinal owns the page; the boy owns the doorway. The reader turns because the most powerful man in France has just learned his name and said it quietly. The name spoken is a balloon; nothing on the letter is legible.""",
    turn="The Cardinal stands for the only time in the book, sees a muddy boy in the last doorway, and reads the boy's name off the letter stolen at Meung.",
    moments=[
        "Panel one, the dominant panel, about 55%, wide and tall: the Cardinal on the RIGHT, standing, the red robe falling straight, turned from the dais toward the long doors along the hall; Rochefort behind him with the white sling; and far down the hall on the LEFT, in the last of the long doors, small but unmistakable against the gold, the boy in muddy ochre with his hat in his hand and his hair in his eyes, looking straight back across the whole room. The Cardinal's question upper right, tail to his mouth; Rochefort's answer below it on his side, tail to his.",
        "Panel two, about 45%, close: the Cardinal's long hand taking a folded cream letter with a broken red seal from the arm of the plain chair beside him and unfolding it, his eyes on the foot of the page; the writing indistinct. Two balloons stacked on his side, the letter line first, the name alone below it, both tails to his mouth.",
    ],
    locks=CARD_BALL.replace("He stands once only, on page 45.", "On this page, and only this page, he STANDS.") + " " + ROCH_SLING + " " + DART_ROAD + " " + MUD + " (small, in the far doorway). " + QUEEN + " The letter keyed to the letters plate, broken-seal state, no legible words.",
    exclusions="Athos, Porthos, Aramis, Constance, and Buckingham are absent from this page; the Queen and court are background only. The Cardinal has no cat. The name is spoken, never written legibly on the letter. No blood. No lettering except the four spoken strings.",
    inputs=["refs/approved/06-cardinal.png", "refs/approved/07-rochefort.png", "refs/approved/01-dartagnan.png", "refs/approved/obj-letters-pass.png", "refs/approved/set-louvre.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All four lines read exactly from the 600 × 900 proof, once each, in causal order; the Cardinal's three hang from the standing man in red and Rochefort's one from the slung man behind him; the name is a balloon and no legible writing appears on the letter. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: the Cardinal stands and turns to see a muddy boy in the far doorway, then reads the boy's name off a letter with a broken seal. If the standing red figure and the small boy in the doorway are not the image the eye finds first, the turn has not landed."),
        ("The Cardinal fails identity or is seated", "Thin, grey pointed beard, red robe and skullcap, STANDING and turned; seated on this page is blocking because this is the only time he stands."),
        ("The boy in the doorway fails", "A clean-shaven black-haired boy in muddy ochre with his hat in his hand must be visible in the last door, looking back. A missing boy or a boy in a cassock is blocking."),
        ("The letter fails", "A folded cream letter with a broken red seal, taken from the chair arm and unfolded; a blue-sealed letter, a sealed letter, or legible words is blocking."),
        ("Focal generation failure", "A duplicated Cardinal, a second scar-man, gross anatomy on the hand unfolding the letter, or a balloon across a face is blocking."),
    ]),

46: dict(
    title="the ring",
    intent="""Dramatic. The gallery of the Louvre. Constance running its length; the boy coming up the gallery stair; they stop a step apart. You did it, she counted, the Cardinal counted, everybody counted; I told you I'd be famous. She takes a ring from a small purse at her waist, puts it in his hand, and closes his fingers over it with both of hers: from the Queen's own hand, taken off when she saw him in the door, and Constance sent running; she said tell him I counted to twelve too; she saw me? everybody saw you, you're wearing two countries. At the rail looking down: the red robe going out by a side door, and after it the sling. He knows my name now, the Cardinal; he looked straight at me and opened a letter, cream with a red seal; the boy has been chasing that letter since Meung and the Cardinal has read his name off it; then he knows the name of the boy who beat him; let him. The dominant turn is the Queen's ring and the boy's name in the Cardinal's mouth. Constance owns the page. The reader turns because there are three men who do not know yet that he arrived.""",
    turn="In the gallery Constance closes the boy's fingers over the Queen's ring and tells him the Queen counted to twelve too, while below the red robe goes out by a side door.",
    moments=[
        "Panel one, about 30%, wide: the gallery, Constance on the RIGHT running its length toward the viewer, the boy on the LEFT coming up the gallery stair, stopping a step apart. Constance's line upper right, tail to her mouth; the boy's answer lower left, after it, tail to his.",
        "Panel two, the dominant panel, about 45%, close and tall: her two hands closing his fingers over a gold ring with one dark stone, the ring visible between their hands; her face and his close over it. Exactly three hands focal: her two on his one. Four balloons as single-speaker beats, alternating and descending: Constance's two lines stacked upper right, tails to her mouth; the boy's three words middle left; Constance's answer lowest right; none level.",
        "Panel three, about 25%: the two of them at the gallery rail on the LEFT and RIGHT, looking down; below, small, the red robe going out by a side door and, after it, a black figure with a white sling. Three balloons A–B: the boy's two lines stacked on his side, tails to his mouth; Constance's last line lower right, after them, tail to hers.",
    ],
    locks=DART_ROAD + " " + MUD + " " + CONST_BALL + " " + RING + " " + CARD_BALL + " (small, below, going out). " + ROCH_SLING + " (small, below).",
    exclusions="Athos, Porthos, Aramis, and Buckingham are absent; the Queen is not on this page. The ring is gold with one dark stone. Constance wears no apron and carries no basket. No blood. No lettering except the nine spoken strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/05-constance.png", "refs/approved/obj-casket-pouch-ring.png", "refs/approved/06-cardinal.png", "refs/approved/set-louvre.png"],
    card=[
        ("Dialogue transcription or ownership fails", "All nine lines read exactly from the 600 × 900 proof, once each, in causal order; Constance's five hang from the girl in the cap and white collar, the boy's four from the muddy boy; each reply sits after the line it answers. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: they meet in the gallery, she closes his hand over a ring from the Queen, they watch the red robe leave below. If her hands closing his over the ring is not the largest image the eye finds, the turn has not landed."),
        ("The ring fails", "A gold ring with one dark stone must be visible passing into the boy's hand; no ring, or a diamond stud instead, is blocking. Exact size is nonblocking."),
        ("Constance or d'Artagnan fails identity", "The small freckled girl in grey with cap and white collar, no apron; the boy clean-shaven in muddy ochre. Blocking if contradicted."),
        ("The figures below fail", "A red-robed figure going out by a side door with a slung black figure after it must be visible below in the last panel; the Cardinal still seated by the dais here is blocking."),
        ("Focal generation failure", "Her two hands and his one on the ring, no extra fingers; a duplicated girl, or a balloon across a face is blocking."),
    ]),

47: dict(
    title="did you arrive?",
    intent="""Dramatic. Late night, the attic. The boy on the bed with his boots still on and the ring on his hand; Constance a step inside by the window; a caption says they came home that night in the order they had stopped. Boots on the stair, and Porthos's head through the door with a second, stranger's hat crammed on top of his own: he won, ate the inn, rode after the boy, never caught him, rode back, did anyone see him, did you arrive? I arrived. Aramis behind him, limping, immaculate, the handkerchief still round his hand: he held the bridge till dark and then, as the Fathers tell us, walked, a long way on one leg; did you arrive? I arrived. Athos last, filling the doorway, hat in hand, looking at the boy; Porthos's face says what Athos smells like: did you arrive? I arrived. Good. Athos, you smell like a hundred barrels; a hundred and six, he counted them, it was a long week. The dominant turn is the three coming home and the same question three times. Athos owns the last word. The reader turns because all four are in one attic and it is nearly morning.""",
    turn="One by one, in the order they stopped, the three come up the attic stair and each asks the boy the same question, and Athos says good.",
    moments=[
        "Panel one, about 25%, wide: the attic late at night by candlelight, the boy on the bed on the LEFT with his boots on and the ring on his hand; Constance a step inside by the window at the back; the door on the RIGHT with Porthos's huge head and shoulders coming through it, a second plain hat crammed on top of his own plumed one. The caption upper left over the dark beam, tail-free. Porthos's line upper right, tail to his mouth; the boy's two words lower left, after it, tail to his.",
        "Panel two, about 25%: Aramis in the doorway on the RIGHT behind Porthos, limping, immaculate, the lace handkerchief still wound round his hand; the boy on the LEFT. Aramis's line upper right, tail to his mouth; the boy's two words lower left, after it, tail to his.",
        "Panel three, the dominant panel, about 50%, close and tall: Athos filling the doorway on the RIGHT, hat in hand, looking at the boy; the boy on the LEFT sitting up; Porthos's face at the edge, nose wrinkled. Five balloons as single-speaker beats, alternating and descending: Athos's question upper right, the boy's two words middle left, Athos's one word below on his side, Porthos's line lower left, Athos's last line lowest right; each tail to its own mouth; none level.",
    ],
    locks=DART_ROAD + " " + MUD + " " + RING + " " + CONST_BALL + " (silent, by the window). " + ATHOS + " " + PORTHOS.replace("black hat with three red ostrich plumes, the largest hat in the book,", "black hat with three red ostrich plumes with a second, plain stranger's hat crammed on top of it,") + " " + ARAMIS + " (limping; the monogrammed lace handkerchief still round his sword hand). " + THREE,
    exclusions="Rochefort, the Cardinal, and Buckingham are absent. Constance is present and silent by the window and must stay in the picture. Athos has no sling. No blood; Aramis limps, nothing is bandaged but the hand. No lettering except the caption and the nine spoken strings.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/02-athos.png", "refs/approved/03-porthos.png", "refs/approved/04-aramis.png", "refs/approved/05-constance.png", "refs/approved/set-house.png"],
    card=[
        ("Dialogue transcription or ownership fails", "The caption and all nine lines read exactly from the 600 × 900 proof, once each, in causal order; each of the three questions hangs from a different man and each of the boy's three answers from the boy; Athos's single word Good sits alone on his side; Constance carries no balloon. " + C1_TAIL),
        ("The turn does not land", "The page must read in order as: Porthos comes through the door with two hats, then Aramis limping, then Athos filling the doorway, and each asks the boy whether he arrived. If Athos in the doorway with the boy answering is not the largest image the eye finds, the turn has not landed."),
        ("The three Musketeers collide", "Porthos huge with red curls, waxed moustache, and two hats; Aramis slim, blond, limping, handkerchief on his hand; Athos tall, dark, pointed beard, no sling. Any two merging is blocking."),
        ("Constance is missing", "The small girl in grey must be visible inside the attic by the window on the page; her absence is blocking."),
        ("d'Artagnan or the ring fails", "Clean-shaven, muddy ochre, boots on, a gold ring with a dark stone on his hand. Blocking if contradicted."),
        ("Focal generation failure", "A fifth companion, a duplicated Musketeer, gross anatomy on Athos's hand with the hat, or a balloon across a face is blocking."),
    ]),

48: dict(
    title="a fair trade",
    intent="""Illustrated prose. Morning, dew, the field behind the Carmelites: the four on the grass by the yellow wall with bread and a bottle, Constance's open basket between them, and the yellow horse drinking from the trough. A smaller image: the boy's hand, the ring on it, holding a piece of bread. The prose counts what he has the way he counted on the bench: the yellow horse nobody will laugh at again, his father's sword, a queen's ring he can never sell or explain, three friends who each held a door, and a man in red somewhere in Paris who knows his name; he came with a letter and calls it a fair trade. The dominant turn is breakfast on the grass and what the boy has now. The four own the page; the horse gets the trough. The reader turns because there is a man in red somewhere in Paris who knows his name and one page left to see him.""",
    turn="At breakfast on the grass where they first met, with the yellow horse drinking from the trough, the boy counts what he has now and calls it a fair trade.",
    moments=[
        "Panel one, the dominant image, about 65%, wide: morning with dew on the Carmelite meadow by the yellow wall; the four sitting on the grass with bread and a bottle, Constance's open wicker basket between them: the boy in ochre, Athos tall and still, Porthos huge and mid-story, Aramis neat with his book; and at the stone trough by the wall the yellow horse drinking. Warm early light.",
        "Panel two, about 35%, close: the boy's hand, the gold ring with its dark stone on it, holding a torn piece of bread.",
        "The prose field sits over the pale yellow wall in panel one, a matte parchment field across most of the width, never over the four or the horse. Three paragraphs. No other lettering.",
    ],
    locks=DART + " (clean coat again or dried mud, hat on; ring on his hand). " + ATHOS + " " + PORTHOS + " " + ARAMIS + " " + THREE + " " + RING + " The yellow horse keyed to its plate, at the trough. Constance is not on this page; only her basket.",
    exclusions="Constance, Rochefort, the Cardinal, and Buckingham are absent. Athos has no sling. Nobody is fighting; all swords sheathed or on the grass. No blood. No lettering except the one prose field.",
    inputs=["refs/approved/01-dartagnan.png", "refs/approved/02-athos.png", "refs/approved/03-porthos.png", "refs/approved/04-aramis.png", "refs/approved/obj-horse.png", "refs/approved/set-carmelite-field.png"],
    card=[
        ("Prose transcription", "The prose field reads exactly, all three paragraphs in order, once, from the 600 × 900 proof, over plain ground and never over the four or the horse, with no other text on the page. " + C1_TAIL),
        ("The breakfast does not own the page", "The eye must find four men at ease on the grass by a yellow wall with a yellow horse drinking from a trough, and second a hand with a ring holding bread. If the hand competes, or the page reads as panels, the turn has not landed."),
        ("The four or the horse fail identity", "The clean-shaven boy, the tall bearded Athos without a sling, the huge red-moustached Porthos, the slim blond Aramis, and a buttercup-yellow horse. A fifth person, a missing one, or a wrong-coloured horse is blocking."),
        ("The ring fails", "A gold ring with one dark stone on the boy's hand in the close image; no ring is blocking."),
        ("Focal generation failure", "Gross anatomy on the hand with the bread, a duplicated Musketeer, or the prose field over a face is blocking. Grass and dew are not."),
    ]),

49: dict(
    title="a man in red at a window",
    intent="""Spectacle. From above and behind: four men walking away from the reader down a narrow Paris street, four abreast, hats on: the small one in ochre in the middle with a hand on his hilt, the huge one with the red plumes, the slim one, the tall one on the outside. In the foreground at the top of the frame, a window with a thin figure in red in it, seated, watching them go, one hand stroking a grey cat on the sill. One caption and the end card. The dominant turn is the four walking away and the red figure who knows the boy's name. The four own the street; the Cardinal owns the window. The reader does not turn: the book ends, and the man in red will be there when there is a next page.""",
    turn="Four men walk away four abreast down a Paris street, and above them at a window a seated man in red with a cat watches them go.",
    moments=[
        "One image, the whole page, about 100%, from above and behind: the top of the frame is the inside edge of a window in a house wall, and in it, close and large, the Cardinal seated in profile or three-quarter from behind, red robe and skullcap, grey pointed beard, one long hand stroking a grey cat that sits on the sill, looking down; below and beyond, the narrow Paris street receding, and walking away from the viewer down its middle, four abreast, hats on: the huge one with three red plumes, the small one in ochre with a hand on his hilt in the middle, the slim one with the white plume, the tall one with the white plume on the outside. Overcast Paris light.",
        "The caption sits along the lower edge over the cobbles, tail-free. The end card sits small at the very bottom below the caption. Nothing else is lettered.",
    ],
    locks=CARD + " (seated at the window, the cat on the sill, seen close from behind or in profile; never standing). " + DART + " " + ATHOS + " " + PORTHOS + " " + ARAMIS + " " + THREE + " The four are seen from behind and above, small; the hats and silhouettes carry identity.",
    exclusions="Constance, Rochefort, and Buckingham are absent. The Cardinal is seated; a standing figure at the window is wrong. The four walk away and do not look back. Exactly four in the street. No blood. No lettering except the caption and the end card.",
    inputs=["refs/approved/06-cardinal.png", "refs/approved/01-dartagnan.png", "refs/approved/02-athos.png", "refs/approved/03-porthos.png", "refs/approved/04-aramis.png", "refs/approved/set-paris.png"],
    card=[
        ("Caption and end card transcription", "The caption and the end card read exactly from the 600 × 900 proof, once each, tail-free, the end card small below the caption, with no other text on the page. " + C1_TAIL),
        ("The page is not four walking away under a red man's window", "The eye must find a seated red figure with a cat at a window in the near foreground and, below, four men walking away four abreast down a street. If the Cardinal is absent, or the four face the viewer, or the page reads as panels, the turn has not landed."),
        ("The Cardinal fails identity or stands", "Thin, grey pointed beard, red robe and skullcap, seated, a grey cat on the sill under his hand. Standing, or no cat, is blocking."),
        ("The four fail as a silhouette group", "Exactly four walking abreast: huge with red plumes, small in ochre in the middle, slim with a white plume, tall with a white plume on the outside. Three or five, or the boy not in the middle, is blocking."),
        ("Focal generation failure", "A duplicated Cardinal, two cats, a fifth walker, or text colliding with a figure is blocking. Rooftop and cobble texture are not."),
    ]),
}
